hylo-lang/hylo

- README.md
- Sources/AST/GenericEnv.swift
- Sources/Basic/Swift+Extensions.swift
- Sources/Eval/Interpreter.swift
- Sources/Eval/RegisterStack.swift
- Sources/Parse/Parser.swift
- Sources/Sema/StmtChecker.swift
- Sources/VIL/Analysis/Typestate.swift
- Sources/VIL/Builder.swift
Dropping `()` was is worth learning a new operator for, and the overload set
creates a potential ambiguity (at least for users): when passed a
never-returning function as 2nd operand, is it being called or just returned?
I think this improves comprehensibility overall.
> Add the missing overload of ?? and use instead of ?>

- .dir-locals.el
- .editorconfig
.dir-locals.el is emacs-specific configuration.
.editorconfig can work across many editors.
> Set up some formatting defaults

- Sources/Compiler/AST/AST.swift
1. It isn't a Collection
2. The thing you get by subscripting it is not the module declaration
3. That it “represents” an AST isn't any different from saying it *is* an AST.
4. Notes to the implementor don't go in doc comments
5. Saying that an array is "a collection with" something is needless.  Saying the modules are “of the AST” is needless; it's a property!
6. Calling the source range of each node a “source range annotation” is needless.
7. Referring to “the AST” is a convention that doesn't scale.  What happens when there's a parameter of `Self` type? 
8. Referring to “the node,” ditto.
If tooling isn't telling us whether a subscript is just for reading or for read/write, without reading a comment, that's pretty sad.
> Omit needless and misleading words, etc.

- Package.swift
Without this, `swift build -c release` produces a warning:
```
'val': warning: found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
//path-to-val/Sources/Compiler/CXX/README.md
```
> Add CXX/README.md to the compiler's resources to silence warning

- Sources/Compiler/AST/Decl/FunDecl.swift
- Sources/Compiler/AST/NodeIDs/NodeID.swift
- Sources/Compiler/AST/NodeIDs/ScopeID.swift
- Sources/Compiler/IR/AbstractTypeLayout.swift
- Sources/Compiler/IR/Emitter.swift
- Sources/Compiler/Parse/Parser.swift
- Sources/Compiler/TypeChecking/ConstraintGenerator.swift
- Sources/Compiler/TypeChecking/ConstraintSolver.swift
- Sources/Compiler/TypeChecking/GenericEnvironment.swift
- Sources/Compiler/TypeChecking/ScopeHierarchy.swift
- Sources/Compiler/TypeChecking/TypeChecker.swift
- Sources/Compiler/Types/LambdaType.swift
- Sources/Compiler/Types/ParameterType.swift
- Sources/Compiler/Types/ProductType.swift
These are standard value-preserving conversions just like `Int.init?(_: String)`, for which the explicitly established convention is "no parameter label."
> Remove 'converting:' label on initializers.

- Sources/Compiler/CXX/CXXTypeExpr.swift
- Tests/ValTests/TestCases/CXX/FunRetInt.val
**Why**
Make progress on transpiler the factorial example. In this step we translate the factorial function (without parameters).
**How**
* treated the case of product types in CXXTypeExpr
* if the Val type is `Int`, transform it to C++ `int`
* add test for functions returning `Int`
**Testing**
* transpiling factorial.val should not crash -> manual inspection
* add test case for function returning `Int`
> Fact return type int

- Sources/Compiler/CXX/CXXModule.swift
- Sources/Compiler/CXX/CXXTypeExpr.swift
- Tests/ValTests/TestCases/CXX/FunIntParam.val
**Why**
Make progress on transpiler the factorial example. In this step we translate the factorial function parameters.
**How**
- translate Val function parameter types to CXX types
- take the bare type from the parameter type when translating a parameter type to C++
- currently ignore the passing convention
**Testing**
- transpiling factorial.val should produce the right declaration for the factorial function
- add test case for function taking an `Int`
> Transpile to C++ function parameters

- Package.swift
- Sources/Utils/BitPattern.swift
You may find [this discussion](https://github.com/apple/swift/issues/48323) interesting - this warning is a bit controversial, but I think the case I fixed here is generally-agreed to be warning-worthy.
> Enable warnings-as-errors; fix two warnings

- Tests/ValTests/ASTTests.swift
There is absolutely no test for the AST's conformance to `Codable`. This PR creates a simple one that just serializes and deserializes an AST.
> Add a simple test case for the AST's conformance to 'Codable'

- .github/workflows/build-and-test.yml
for faster test failure feedback in most cases.
> Test the debug build before building release

- Tests/ValTests/CXXTests.swift
- Tests/ValTests/TestCases/CXX/EmptyMain.val
- Tests/ValTests/TestCases/CXX/FactorialExample.val
- Tests/ValTests/TestCases/CXX/VoidReturn.val
**Why?**
Improve CXX transpiler tests, to ease the development of CXX transpiler
**What?**
- display the name of the test file when a test fails
- separate the `cpp` annotations into two annotations: one for source files, and one for headers
- add test for factorial transpilation -- this may be brittle at the beginning, but it will help in the development
**Testing**
- all unit tests must pass
- manual testing to ensure testing framework work as expected
> Tests improvements

- Sources/Compiler/TypeChecking/ConstraintSolver.swift
- Sources/Compiler/TypeChecking/SubstitutionMap.swift
- Shouldn't be a collection; things whose order is not salient should _have_, rather than _be_ collections.  Let's not compound Swift's error.  Plus nobody's using the functionality.
- flattened() was badly named and documented; the flattening is below the level of the client's abstraction.
> SubstitutionMap cleanup

- Sources/Compiler/CXX/CXXModule.swift
- Sources/Compiler/CXX/CXXTranspiler.swift
- Sources/Compiler/IR/Emitter.swift
- Sources/Compiler/IR/Module.swift
- Sources/Compiler/TypeChecking/TypedDeclProperty.swift
- Sources/Compiler/TypedNode.swift
The current syntax of `Typed<AST.Node>` is ugly. We want to make it easier to use.
Instead of that syntax, introduce an inner type alias in each AST node, so that we can write `Node.Typed` to get the typed node from an AST node.
> Inner typed

- Sources/Compiler/IR/InstructionIndex.swift
The rationale here is that there isn't really a single notional collection of instructions, and if there were, at block and function boundaries, there's no single insertion position.
> InstructionIndex doc wording

- Sources/CLI/main.swift
- Sources/Core/Constraints/FunctionCallConstraint.swift
- Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
The PR allows the type checker to infer the type of an integer literal based on the result of an overload constraint. For example:
```
fun fn(x: Int) -> Int {}
fun fn(x: Double) -> Double {}
let _ : Double = fn(x: 1)
}
```
The solver is allowed to infer `1` has type `Double` after overload resolution concludes `fn` has type `[] (x: Double) -> Double`.
> Improve type inference for integer literals

- Sources/Core/AST/NodeIDs/NodeID.swift
- Sources/Core/TypedNode.swift
It seems like `ConcreteNodeID` was requiring a copy initializer. Since all types are copyable in Swift, it should be sufficient to just use copy-initialization with `=`, as shown with the suggested change in `TypedNode.swift`.
> Remove needless copy initializer

- Docs/CLI.md
- Sources/CLI/main.swift
- Sources/Core/AST/NodeIDs/NodeID.swift
- Sources/Core/Constraints/OverloadConstraint.swift
- Sources/Core/SourceFile.swift
- Sources/Core/SourceLocation.swift
- Sources/Core/SourceRange.swift
- Sources/FrontEnd/TypeChecking/ConstraintSolver.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Tests/ValTests/SourceFileTests.swift
This PR implements support for logging how type constraints are being solved.
Usage example:
```bash
valc --typecheck --trace-inference main.val:16 main.val
```
This command will type check `main.val` and show a trace of the type constraint solver for all root expressions at line 16 of `main.val`.
> Solver tracer

- Sources/Core/Types/ExistentialType.swift
- Sources/Core/Types/InstantiatedType.swift
- Sources/IR/InstructionID.swift
- Sources/IR/InstructionIndex.swift
Swift 6 will disallow use of modules without an explicit include in the source file.  Add the missing includes in a few sites that trigger this issue.
> explicitly include `Utils`

- Sources/Core/TypedNode.swift
- Sources/IR/AbstractTypeLayout.swift
- Sources/IR/Analysis/LifetimePass.swift
- Sources/IR/Emitter.swift
- Sources/IR/Operands/Instruction/AllocStackInstruction.swift
- Sources/IR/Operands/Instruction/BorrowInstruction.swift
IR code used in a few occasions untyped nodes. Use typed nodes instead.
This is a continuation of the effort to use typed nodes instead of pairing AST nodes with TypedProgram.
> Use typed nodes in the IR code

- Docs/CLI.md
- Sources/CLI/main.swift
* Added all options to CLI.md
* Options are described in the same order as presented in the CLI usage
* Prefer alphabetical or a more "most likely used" ordering?
* Specified supported emit values in CLI help
* resolves #41
* This multi-line option help is non-standard and does set a precedence for wordy help in the future.
* Prefer a comma-delimited list and leave it to CLI.md to describe the options?
* Minor edits to --trace-inference and -o for clarification
CLI before:
```bash
$ valc
Error: Missing expected argument '<inputs> ...'
USAGE: valc [--modules] [--import-builtin] [--no-std] [--typecheck] [--trace-inference <trace-inference>] [--emit <emit>] [-o <o>] [--verbose] [<inputs> ...]
ARGUMENTS:
<inputs>
OPTIONS:
--modules               Compile inputs as separate modules. …
```
> Update CLI documentation

- Sources/CodeGen/CXX/README.md
Add tables with how the Val nodes would be transpiled into CXX nodes (not yet complete). This forms a rough plan on what CXX nodes we need to build and how different Val structures translate to those nodes.
> Add translation plan to CXX transpiler documentation

- Tests/ValTests/Utils/XCTest+Shims.swift
We cannot change the API of the types in XCTest+Shims.swift. Everything in this file is meant to reproduce XCTest's API on non-Apple platforms.
> Fix XCTest shims

- .github/workflows/build-and-test.yml
So we don't have to wait quite so long for CI results
> Remove needless build-and-test steps

- Sources/CodeGen/CXX/CXXTranspiler.swift
- Sources/CodeGen/CXX/Stmt/CXXReturnStmt.swift
- Tests/ValTests/TestCases/CXX/Stmt/ExpressionFunction.val
- Tests/ValTests/TestCases/CXX/Stmt/ReturnExpr.val
- Tests/ValTests/TestCases/CXX/Stmt/ReturnVoid.val
Add possibility to emit CXX return statements from Val `return` statements, with or without returning value.
Add tests to cover cases in which `CXXReturnStmt` needs to be emitted:
- function implicitly returning a value
- explicit `return` statement without any value
- explicit `return` statement with value
> Emit cxx return

- Sources/CodeGen/CXX/CXXModule.swift
- Sources/CodeGen/CXX/CXXTranspiler.swift
- Sources/CodeGen/CXX/Decl/CXXClassAttribute.swift
- Sources/CodeGen/CXX/Decl/CXXClassDecl.swift
- Sources/CodeGen/CXX/Decl/CXXFunctionDecl.swift
- Sources/CodeGen/CXX/Decl/CXXTopLevelDecl.swift
- Tests/ValTests/TestCases/CXX/SimpleType.val
The CXX transpiler is lacking the ability to emit C++ classes from Val product types.
Add support for emitting classes. The support, at this point, is just basic: we know to write the attributes of simple product types.
We now have 2 top-level declaration types that can be translated into a C++ module: functions and classes. Both of them need to be able to write the "header part" and the "source part".
Testing:
*  add a simple test to show translation of a Point type
> Emit classes

- .github/workflows/build-and-test.yml
Causes CI to fail if our code coverage slips; generates a coverage report with every run.
Currently only checks coverage on ubuntu (the GH action plugin only supports that).  This could certainly be improved by making it work on all OSes and eliminating warnings (and there are other plugin options we can explore) but this will suffice to make sure we don't backslide on testing.  We'll have to update the MINIMUM_COVERAGE as we improve things
> Measure/maintain code coverage in CI

- Package.resolved
- Package.swift
- Sources/Core/SourceFile.swift
- Sources/Utils/Algorithms.swift
The theory is that depending on Swift Numerics indirectly via two paths is the root cause.
Before this PR, BigInt and Swift-Algorithms both pull in swift-numerics.
/cc @compnerd
> Attempt to work around Windows CI problem

- Sources/CLI/SourceRange+Extensions.swift
Recent changes on `SourceRange` broke its conformance to `ExpressibleByArgument`.
> Fix 'SourceRange.init(argument:)'

- Sources/CodeGen/CXX/CXXTranspiler.swift
- Sources/CodeGen/CXX/Stmt/CXXExprStmt.swift
- Tests/ValTests/TestCases/CXX/Stmt/ExprStmt.val
- Tests/ValTests/TestCases/CXX/Stmt/ExprStmtFromBinding.val
- Tests/ValTests/TestCases/CXX/Stmt/ReturnVoid.val
Val's `ExprStmt` would be translated into a `CXXExprStmt`. Also, bindings without any pattern will result in a `CXXExprStmt` (with a `CXXVoidCast`)
> Emit CXX expression statements

- Library/Core/Int.val
- Sources/FrontEnd/Parse/Parser.swift
- Tests/ValTests/ParserTests.swift
This change improves the consistency of the grammar (see https://github.com/val-lang/val-lang.github.io/discussions/43).
> Parse operator notations after function introducers

- Sources/CodeGen/CXX/CXXTranspiler.swift
- Sources/CodeGen/CXX/Stmt/CXXBreakStmt.swift
- Sources/CodeGen/CXX/Stmt/CXXContinueStmt.swift
- Sources/CodeGen/CXX/Stmt/CXXDoWhileStmt.swift
- Sources/CodeGen/CXX/Stmt/CXXIfStmt.swift
- Sources/CodeGen/CXX/Stmt/CXXWhileStmt.swift
- Sources/Core/ScopedProgram.swift
- Sources/FrontEnd/Parse/Parser.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Tests/ValTests/TestCases/CXX/Stmt/ContinueAndBreak.val
- Tests/ValTests/TestCases/CXX/Stmt/DoWhileStmt.val
- Tests/ValTests/TestCases/CXX/Stmt/IfStmt.val
- Tests/ValTests/TestCases/CXX/Stmt/WhileStmt.val
Basic code to emit Val statements to CXX.
This does not include `for` and `yield` statements, as they require more complex semantics.
Add basic tests to cover some simple scenarios.
> Emit cxx control stmt

- Sources/Core/AST/AST.swift
- Sources/Core/SourceFile.swift
- Sources/Utils/FactoryInitializable.swift
- Sources/Utils/SharedMutable.swift
- Sources/Utils/StatefulCoder.swift
- Sources/ValCommand/ValCommand.swift
- Tests/ValTests/ASTTests.swift
`SourceFile` contents are now serialized separately from the AST, with the AST just recording an integer ID for each distinct source file.  The lifetime of contents are now maintained by a threadsafe global dictionary.
I apologize in advance for the fact that the constituent commits are not particularly meaningful.  I will try to reorganize if any reviewer wants me to; otherwise it should probably be squashed.
> Properly serialize/deserialize source files

- Sources/FrontEnd/TypeChecking/TypeChecker+ConstraintGeneration.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Tests/ValTests/TestCases/TypeChecking/MatchExpr.val
This PR implements the first step of inferring the type of match expression: visiting the patterns of the match cases and make sure they correspond to the type of the subject.
The changes in the PR do not cover constraint generation for the body of each individual case yet, which should be submitted as a separate patch.
> Visit the match expression patterns during type inference

- Sources/CodeGen/CXX/CXXTranspiler.swift
- Tests/ValTests/TestCases/CXX/Expr/InfixOperators.val
- Tests/ValTests/TestCases/CXX/Expr/PrefixOperators.val
- Tests/ValTests/TestCases/CXX/FactorialExample.val
- Tests/ValTests/TestCases/CXX/FunIntParam.val
- Tests/ValTests/TestCases/CXX/FunRetInt.val
- Tests/ValTests/TestCases/CXX/SimpleType.val
- Tests/ValTests/TestCases/CXX/Stmt/AssignStmt.val
- Tests/ValTests/TestCases/CXX/Stmt/ContinueAndBreak.val
- Tests/ValTests/TestCases/CXX/Stmt/ExpressionFunction.val
- Tests/ValTests/TestCases/CXX/Stmt/ReturnExpr.val
The code will blindly transform all `Int` types into `Int`, even there is no C++ definition for `Int.
This will later be addressed when we translate Val standard library to C++.
> Stop translating Val `Int` into C++ `int`.

- Sources/FrontEnd/TypeChecking/TypeChecker+ConstraintGeneration.swift
- Tests/ValTests/TestCases/TypeChecking/CallInit.val
Compiler used to crash when inferring the type of a call to an undefined initializer.
> Fix handling of undefined initializers

- Library/Core/Process.val
- Sources/Core/Types/BuiltinSymbols.swift
LLVM doesn't have a `terminate` instruction, so it's likely we'll have to import a C or C++ function to implement that feature. The current PR replaces the `Builtin.terminate` by an abort function exposed through a FFI.
> Replace 'Builtin.terminate' by 'abort'

- Library/Core/Double.val
- Sources/Core/BuiltinFunction.swift
- Sources/Core/Types/BuiltinSymbols.swift
- Sources/Core/Types/BuiltinType.swift
- Sources/Core/Types/LambdaType.swift
- Sources/FrontEnd/TypeChecking/TypeChecker+ConstraintGeneration.swift
- Sources/Utils/Operators.swift
- Tests/ValTests/BuiltinFunctionTests.swift
This PR creates an abstraction to represent built-in functions in the compiler.
This abstraction is not used during type checking or lowering yet, to avoid bloating the size of the patch.
> Create an abstraction representing built-in functions

- Sources/FrontEnd/TypeChecking/ConstraintSolver.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
> Rename 'TypeChecker.decl(_:named)' to 'decl(in:named:)'

- Sources/Core/SourceFile.swift
- Tests/ValTests/CaptureCollectorTests.swift
- Tests/ValTests/LexerTests.swift
- Tests/ValTests/ParserTests.swift
- Tests/ValTests/SourceFileTests.swift
- Tests/ValTests/Utils/TestFile.swift
_Re-open #329 with corrected branch name_
Using `testCode(_:)` instead of `SourceFile.init(synthesized:)` doesn't seem to improve call sites so much, yet it costs an additional free function that can only be used in the `ValTests` target. It is also not obvious what the result of this function is; it doesn't actually test anything, it only creates a source file with the given text.
The changes make `SourceFile` conform to `ExpressibleByStringLiteral` so that we can write:
```swift
let s: SourceFile = """
import Foo
fun main() {}
"""
```
> Remove 'testCode(_:)'

- Sources/Core/Types/AnyType.swift
- Sources/Core/Types/AssociatedTypeType.swift
- Sources/Core/Types/GenericTypeParameterType.swift
- Sources/Core/Types/InstantiatedType.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
`AnyType.specialized` had a bug that create ill-formed associated types.
> Fix specialization

- Sources/Core/AST/AST.swift
- Sources/Core/AST/Name.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
This PR introduces a subscript on `AST` to project a sequence of nodes given their positions. The goal is to avoid the following recurring pattern, which mostly occurs in the type checker:
```swift
let labels = program.ast[n].parameters.map({ program.ast[$0].label?.value })
```
The new subscript makes it possible to write:
```swift
let labels = program.ast[program.ast[n]].map(\.label?.value)
```
I was hoping for more code reduction, but I think the patch still improves a handful of use sites.
> Simplify sequence transformations requiring AST access

- Tests/ValTests/TestCases/Lowering/Loops.val
The new test is currently crashing the compiler because of a bug in the definite initialization pass.
> Test lowering of while loops

- Sources/IR/AbstractTypeLayout.swift
- Sources/IR/Analysis/DefiniteInitializationPass.swift
This patch modifies how `DefiniteInitializationPass.Object`s are represented so that they store their own type. This change makes simplify the APIs of `Context..withObject(...)` and `Object.withSubobject` which can now compute objects layout internally, without taking seemingly unrelated parameters.
> Simplify the API of abstract objects in DI

- Sources/IR/Analysis/DefiniteInitializationPass.swift
- Sources/IR/Emitter.swift
- Sources/IR/Module+Description.swift
- Sources/IR/Operands/Instruction/ElementAddrInstruction.swift
This patch adds an instruction `element_addr` to compute the address of stored properties. It's meant to uncouple address computation from the `borrow` instruction
> Refactor address computation

- .github/workflows/build-and-test.yml
Windows CI fails too often. Perhaps try updating Swift for Windows again?
> Update `windows-tag` of Swift in CI

- Sources/Core/Diagnostic.swift
Fixes #326.  Please don't fight me on this; capturing these so they show up nicely in XCode is a separate step and must be done explicitly.
> Fix printed format of Diagnostic so it is recognized by IDE(mac)s.

- Sources/Core/SourceFile.swift
- Tests/ValTests/CaptureCollectorTests.swift
- Tests/ValTests/ParserTests.swift
During testing, allows unexpected diagnostic reports from Val source code in Swift multiline string literals to point back at the exact place in the original String literal where the problem occurred.
If you insert errors into the source that's now constructed with `SourceFile.diagnosableLiteral` you can see the results for yourself.
> Diagnosable sourcefile literals for testing

- Sources/FrontEnd/TypeChecking/ConstraintSystem.swift
- Sources/FrontEnd/TypeChecking/GenericEnvironment.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
Before this PR, `TypeChecker.conformedTraits(of:in:)` and `TypeChecker.realize(conformances:in:)` would return `nil` as soon as they encountered an invalid type expression, compelling all call sites to unwrap the result.
> Refactor conformance enumeration

- Sources/IR/Analysis/AbstractContext.swift
- Sources/IR/Analysis/AbstractDomain.swift
- Sources/IR/Analysis/AbstractLocation.swift
- Sources/IR/Analysis/AbstractObject.swift
- Sources/IR/Analysis/AbstractValue.swift
- Sources/IR/Analysis/Module+NormalizeObjectStates.swift
This PR factors out the data structures that will be reused by the different abstract interpreters implementing flow-sensitive IR analysis.
> Factor out support for abstract interpretation

- Sources/IR/Analysis/AbstractInterpreter.swift
- Sources/IR/Analysis/Module+NormalizeObjectStates.swift
- Sources/IR/Analysis/Module+Ownership.swift
Two phases of the IR analysis/transformation pipeline are implemented as abstract IR interpreters, which share a significant part of their logic. In an effort to avoid code duplication, I tried to factor out these common parts.
The main contribution of this PR is `AbstractInterpreter`. This type represents the state of an abstract interpreter and implements the algorithm for selecting the basic blocks to process and forming the abstract evaluation contexts in which their IR is interpreted. It is used as follows: https://github.com/val-lang/val/blob/36b01ba1a0d669b25bb2d2a7e4310199e0b6d7f0/Sources/IR/Analysis/Module%2BOwnership.swift#L12-L36
The closure passed to `AbstractInterpreter.fixedPoint` will be called for each block to process until a fixed point is reached.
> Factor out the infrastructure shared by abstract interpreters

- Tests/EndToEndTests/ExecutionTests.swift
- Tests/ValCommandTests/ValCommandTests.swift
These tests have begun to fail in Linux CI without explanation. In the interest of prioritizing ongoing LLVM work, this PR disables the tests.
> Disable three tests related to --emit binary

- .gitignore
- .vscode/extensions.json
- README.md
This should have been added with #535. Adds recommended extensions for VSCode including the devcontainer extension, and also adds README instructions for using Devcontainers in VSCode.
> README for using Devcontainers

- Sources/Core/Constraints/FunctionCallConstraint.swift
- Sources/FrontEnd/TypeChecking/ConstraintSystem.swift
- Sources/FrontEnd/TypeChecking/TypeChecker+ConstraintGeneration.swift
- Sources/FrontEnd/TypeChecking/TypeChecker+Diagnostics.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Tests/ValTests/TestCases/TypeChecking/DefaultFunctionArgument.val
This patch refactors the type inference algorithm for function calls in preparation to support default arguments.
Before the patch, constraint generation would attempt to propagate type information down the AST at function calls to refine the inference of call arguments. This strategy aimed at reducing the size of the generated constraint system. However, it can't apply when the type of the callee must be inferred from context. In this case, the constraint solver will first have to determine the callee's type and then check if the inferred type of the call's arguments match. So that means in general, the constraint solver must be able to propagate type information in both directions. Therefore, implementing top-down propagation during constraint solving involves some amount of code …
> Refactor type inference for function calls

- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Tests/ValTests/TestCases/TypeChecking/ExtensionOfImport.val
`TypeChecker.extendingDecls(of:exposedTo:)` was inconditionally looking into all modules imported of the AST, not exluding those that are not visible to the scope from which lookup originated.
As a result, name lookup could gather extensions declared in non-dependent modules and cause resolution failures.
> Fix a bug in extension lookup

- Sources/Core/CompileTimeValues/GenericArguments.swift
- Sources/Core/Constraints/ConstraintSet.swift
- Sources/Core/Constraints/OverloadConstraint.swift
- Sources/Core/DeclReference.swift
- Sources/Core/TypedNode.swift
- Sources/Core/TypedProgram.swift
- Sources/Core/Types/BoundGenericType.swift
- Sources/FrontEnd/TypeChecking/BindingMap.swift
- Sources/FrontEnd/TypeChecking/ConstraintSystem.swift
- Sources/FrontEnd/TypeChecking/GenericArguments.swift
- Sources/FrontEnd/TypeChecking/NameResolutionResult.swift
- Sources/FrontEnd/TypeChecking/Solution.swift
- Sources/FrontEnd/TypeChecking/TypeChecker+ConstraintGeneration.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/IR/Emitter.swift
- Sources/Utils/CustomWitnessedSet.swift
- Sources/Utils/EquatableWitness.swift
- Sources/Utils/HashableBox.swift
- Sources/Utils/HashableWitness.swift
To support monomorphization, the emitter should have access to the generic arguments that were used to infer the types of all expressions.
> Remember generic arguments

- .github/workflows/build-and-test.yml
- Sources/Core/AST/AST.swift
- have build steps build the tests too
- ensure multi-part build steps fail if any part fails (using the bash shell apparently also does this)
- eliminate a broken/illegal import that was causing some tests to fail
- stop enabling code coverage where we don't use it
- create and use `llvm.pc` without `sudo`.
> CI improvement bundle

- Sources/ValCommand/ValCommand.swift
We don't need to write that `init` explicitly.
> ValCommand.OutputType: make more declarative

- .github/workflows/build-and-test.yml
- Sources/Utils/FileManager+Extensions.swift
- Sources/ValCommand/ValCommand.swift
- Tests/EndToEndTests/ExecutionTests.swift
- Tests/ValCommandTests/SourceLineExtensionsTests.swift
- Tests/ValCommandTests/ValCommandTests.swift
I noticed during local parallel testing that Val.o was sometimes reported by the linker as having length 0.  I think that's because it was being written directly into FileManager.default.temporaryDirectory, and testing processes were stomping on one another.
> Make parallel testing work locally.

- Sources/Core/AST/AST.swift
- Sources/FrontEnd/TypeChecking/TypeChecker+Diagnostics.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/IR/Emitter.swift
- Tests/EndToEndTests/TestCases/Factorial.val
This patch gets rid of needless moves when a binding is initialized with the result of a constructor call.
> Refactor initialization

- Sources/Core/Program.swift
- Sources/Core/SourceRange.swift
- Sources/IR/Analysis/Module+Depolymorphize.swift
- Sources/IR/Block.swift
- Sources/IR/Emitter.swift
- Sources/IR/Function.swift
- Sources/IR/Module.swift
Tracking lexical scopes in basic blocks will allow us to query conformances to specific traits during IR analysis.
> Track lexical scopes in basic blocks

- Sources/Core/AST/Decl/BindingDecl.swift
- Sources/Core/AST/Decl/ConformanceDecl.swift
- Sources/Core/AST/Decl/ExtensionDecl.swift
- Sources/Core/AST/Decl/FunctionDecl.swift
- Sources/Core/AST/Decl/InitializerDecl.swift
- Sources/Core/AST/Decl/MethodDecl.swift
- Sources/Core/AST/Decl/NamespaceDecl.swift
- Sources/Core/AST/Decl/OperatorDecl.swift
- Sources/Core/AST/Decl/ProductTypeDecl.swift
- Sources/Core/AST/Decl/SubscriptDecl.swift
- Sources/Core/AST/Decl/TraitDecl.swift
- Sources/Core/AST/Decl/TypeAliasDecl.swift
- Sources/Core/AST/DeclModifiers/AccessModifier.swift
- Sources/FrontEnd/Parse/Lexer.swift
- Sources/FrontEnd/Parse/Parser+Diagnostics.swift
- Sources/FrontEnd/Parse/Parser.swift
- Sources/FrontEnd/Parse/Token.swift
- Tests/ValTests/LexerTests.swift
- Tests/ValTests/ParserTests.swift
This PR adds support for the `private` access modifier (#84), as discussed with @kyouko-taiga.
It is possible to mark functions, method, binding, etc. declaration explicitly as `private`, e.g.,:
```
private fun my_private_function(_ a: let Int, _ b: let Int) -> Int { ... }
```
Furthermore, any declaration without access modifiers is treated implicitly as private.
We may consider a changing the `SourceRange` of the implicitly "generated" private access modifiers.
> `private` Access Modifier

- Sources/Core/DeclReference.swift
- Sources/FrontEnd/TypeChecking/NameResolutionResult.swift
- Sources/FrontEnd/TypeChecking/SubstitutionMap.swift
- Sources/FrontEnd/TypeChecking/TypeChecker+ConstraintGeneration.swift
- Sources/FrontEnd/TypeChecking/TypeChecker+Diagnostics.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/IR/Emitter.swift
- Tests/ValTests/TestCases/TypeChecking/GenericParameters.val
- Tests/ValTests/TestCases/TypeChecking/IllegalExtension.val
This PR is the first of a series of changes steps aimed at refactoring the evaluation of type expressions.
> Refactor the way extensions are bound

- Library/Val/Core/Pointer.val
- Tests/EndToEndTests/TestCases/AddressOf.val
This PR proposes a simplistic implementation of `Pointer<Pointee>` that can be used to get a pointer to a local value.
> Implement `Pointer<Pointee>`

- Library/Val/Core/Pointer.val
- Sources/Core/TypeRelations.swift
- Sources/Core/TypedProgram.swift
- Sources/IR/Analysis/Module+Depolymorphize.swift
- Tests/EndToEndTests/TestCases/AddressOf.val
Before the patch, monomorphization would not properly apply the parameterization of a generic function called in another generic function. For example:
```swift
fun use_0<T>(_ x: T) {}
fun use_1<T>(_ x: T) { use_0(x) }
let i = 42
use_1(i)
}
```
> Fix monomorphization of generic uses nested in generic functions

- Sources/IR/Analysis/Module+Depolymorphize.swift
- Sources/IR/Function.swift
- Sources/IR/Module.swift
“Function parameters” already means something else.
> Function.parameters => Function.genericParameters

- Sources/IR/Analysis/Module+Depolymorphize.swift
- Sources/IR/Operands/Constant/FunctionReference.swift
- Sources/IR/Operands/Instruction/CallInstruction.swift
"function argument" already has a different meaning
> FunctionReference.arguments => genericArguments

- Library/Val/Core/Bitcast.val
- Sources/Core/AST/Decl/Decl.swift
- Sources/Core/AST/Decl/FunctionDecl.swift
- Sources/Core/AST/Decl/InitializerDecl.swift
- Sources/Core/AST/Decl/MethodDecl.swift
- Sources/Core/AST/Decl/MethodImpl.swift
- Sources/Core/AST/Decl/ProductTypeDecl.swift
- Sources/Core/AST/Decl/SubscriptDecl.swift
- Sources/Core/AST/Decl/SubscriptImpl.swift
- Sources/Core/AST/Decl/TraitDecl.swift
- Sources/Core/AST/Decl/TypeAliasDecl.swift
- Sources/Core/AST/TypeScope.swift
- Sources/Core/CompileTimeValues/GenericArguments.swift
- Sources/Core/Program.swift
- Sources/Core/Types/BoundGenericType.swift
- Sources/FrontEnd/TypeChecking/ConstraintSystem.swift
- Sources/FrontEnd/TypeChecking/Constraints/OverloadConstraint.swift
- Sources/FrontEnd/TypeChecking/NameResolutionContext.swift
- Sources/FrontEnd/TypeChecking/NameResolutionResult.swift
- Sources/FrontEnd/TypeChecking/SubstitutionMap.swift
- Sources/FrontEnd/TypeChecking/TypeChecker+ConstraintGeneration.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Tests/EndToEndTests/TestCases/AddressOf.val
- Tests/ValTests/TestCases/TypeChecking/NestedGenerics.val
This PR refactors name resolution to enforce the invariants mentioned in #765 and fix type inference through generic members.
It introduces one regression: generic arguments to static declarations nested in generic members can no longer be inferred. However, the fact that it was working with a few select examples was a happy coincidence. A proper implementation will require a general strategy to describe when and where generic arguments can be elided. In the meantime, we can workaround the regression by providing explicit arguments. See `Bitcast.val` and `AddressOf.val` for examples.
> Fix type inference through generic members

- Sources/FrontEnd/Parse/Lexer.swift
- Sources/FrontEnd/Parse/Parser.swift
- Sources/FrontEnd/Parse/Token.swift
- Tests/ValTests/LexerTests.swift
- Tests/ValTests/ParserTests.swift
This PR adjusts the way integers and floats are tokenized and parsed, fixing the tuple key path parsing issue described in https://github.com/val-lang/val/issues/783
Specifically, floats are no longer tokenized as a single .float token. Instead, they are broken down into parts like .int, .dot, and .exponent. This change allows for more granular control over the tokenization process and directly resolves the aforementioned issue.
**Tokenization Changes:**
- **Before this PR:**
- The floating-point number `1.12e+123` was tokenized as: `.float "1.12e+123"`
- **After this PR:**
- The floating-point number `1.12e+123` is now tokenized as:
- `.int, "1"`
- `.dot, "."`
- `.int, "12"`
- `.exponent, "e+123"`
Fixes https://github.com/val-lang/val/issues/783
> Refactor Integer and Float Tokenization/Parsing for Future Parsing Issue Fix

- Package.resolved
- Package.swift
The most salient change is [here](https://github.com/val-lang/val/pull/828/files#diff-f913940c58e8744a2af1c68b909bb6383e49007e6c5a12fb03104a9006ae677eR37-R38); the rest is the result of running `swift package update`. 
This change removes our dependency on our [fork of swift-format](https://github.com/val-lang/swift-format), which was put in place to reduce inconsistency between local dependency versions and those available on CI; namely `swift-format` and `swift-syntax`. The inconsistencies would produce build errors on CI which would not show up on local runs of `Tools/run-swift-format.sh -d lint`.
The forked repo attempted to lock the version of swift-format by [committing a `Package.resolved`](https://github.com/apple/swift-format/compare/main...val-lang:swift-format:main) file that …
> Update Swifty-LLVM and Swift Syntax packages

- Sources/FrontEnd/Parse/Lexer.swift
This PR corrects the tokenization of exponents that are not followed by a valid integer. Previously, parsing a string like "1e" would incorrectly tokenize the "e" as an empty invalid token. With this correction, the lexer now tokenizes the "e" as an invalid token containing the character "e".
Changes made:
- Adjusted the handling of exponent tokenization to extend the token site even if the integral literal scanning fails.
The following test case now passes:
```
TokenSpecification(.int, "1"),
TokenSpecification(.invalid, "e")
```    
for the source `"1e"`
Prior to this PR, the following line was failing:
https://github.com/val-lang/val/blob/7325df1efeb3378a322a43f62709b0d302c49dc1/Tests/ValTests/LexerTests.swift#L112
> Fix Exponent Tokenization to Handle Missing Integer Part

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- ~~I made the repository links go to `hylo-lang/hylo` as I figured the repo will get renamed very shortly. Let me know if this is incorrect~~
- On line 38 (now 41) It said "That's Val compiler!" this seems grammatically incorrect to me so I changed it to "That's Hylo's compiler!" it could also be "That's the Hylo compiler!" if you prefer.
- I added a warning about broken links and confusion to the top of the README. Let me know if this is OK or if I should remove it
- I just renamed the site in the email in `CODE_OF_CONDUCT.md`. Please verify this is correct
The repo was renamed while I was typing. I'll fix it right quick
- I just also fixed CONTRIBUTING.md and CODE_OF_CONDUCT.md since they seemed straight forward
> Update README to use the new name where possible

- .spi.yml
This configures SPI to
- use a custom base image when building on Linux
- use Linux and Swift 5.9 to generate docs
See https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/2545 for details
> Finestructure patch 1

- Sources/CodeGen/LLVM/Transpilation.swift
- Sources/Core/Types/TupleType.swift
- Sources/FrontEnd/TypedProgram.swift
- Sources/IR/Operands/Instruction/SubfieldView.swift
This PR partially addresses #758. A complete fix requires associated type requirement checking, which has not been implemented yet.
> Generate metatypes for tuple types

- .github/workflows/doc-extraction.yml
- Tools/retry-once
Either Github actions or swift package manager is causing some build jobs to die non-deterministically without a diagnostic.  Retry these jobs once before reporting failure.
> Add some insurance against spurious failures in doc extraction.

- .github/workflows/format-check.yml
An attempt to stomp out the spurious format-check failures we've been seeing, that [die in setup-swift](https://github.com/swift-actions/setup-swift/issues/591).
An alternative would be to run the format check on MacOS, but that's expected to be slower.  This analysis <https://github.com/swift-actions/setup-swift/issues/591#issuecomment-1684602660> explains why I think it would work.
Another alternative would be to run it on Linux in the devcontainer, where Swift is already set up.
> Use a different action to setup swift on Linux.

- Library/Library.swift
- Sources/FrontEnd/AST+Extensions.swift
...instead of copying them to a resources directory and building from there.
Fixes #932
> Build the standard library from the sources in the repo working copy

- .github/workflows/doc-extraction.yml
Contributors may want to run actions on their own forks of hylo. The GitHub pages publishing action should always be excluded in such a run.
> Add conditional to publishing actions

- Sources/IR/Emitter.swift
> Ignore unused rvalues during IR lowering

- Library/Hylo/Core/PointerToMutable.hylo
- Library/Hylo/Pointers+DynamicAllocation.hylo
- Sources/CodeGen/LLVM/Transpilation.swift
- Tests/LibraryTests/TestCases/PointerToMutableTests.hylo
- Added missing case for .advancedByBytes in transpilation. This code
was based on similar code in this file.
- Added PointerToMutable<Never>.advance specialized function. This
needed to be specialized because of issue #985. The general version
wasn't added because of issue #989.
This code is required to enable `DynamicBuffer` to provide a pointer
to the beginning of its elements. We need this to ultimately implement
`Array`.
> Fix Builtin.advanced_by_bytes and add PointerToMutable.advance

- LICENSE
Add the linking exception discussed in #890, which is the same as the one used in Swift.
> Add a linking exception to the license

- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/IR/Analysis/Module+AccessReification.swift
- Sources/IR/Analysis/Module+CallBundleReification.swift
- Sources/IR/Emitter.swift
- Sources/IR/Mangling/Demangler.swift
- Sources/IR/Mangling/Mangler.swift
- Sources/IR/Mangling/ManglingOperator.swift
- Sources/IR/Module.swift
- Tests/EndToEndTests/TestCases/MethodBundle.hylo
This PR lays down the foundations for compiling calls to method bundles. It only implements an embarrassingly primitive bundle reification pass that does not perform last use analysis to pick the appropriate variant in a bundle. This feature should be addressed in another PR.
> Implement IR support for method bundles

- Sources/IR/Emitter.swift
- Tests/HyloTests/TestCases/Lowering/EmptyStruct.hylo
Fixes: https://github.com/hylo-lang/hylo/issues/997
Alternative approach to https://github.com/hylo-lang/hylo/pull/1014
> Empty struct init alternate

- Sources/Core/AccessEffectSet.swift
- Sources/IR/Emitter.swift
A conformance to 'Collection' provides more algorithms than one to 'Sequence' without neagtively impacting performance.
> Make 'AccessEffectSet.Elements' conform to 'Collection'

- .github/workflows/markdown-link-check.yml
- CONTRIBUTING.md
- Docs/CompilerArchitecture.md
This adds a document on the high level overview of the hylo compiler. Feel free to adjust and extend it. It's just a starting point.
Since it links to various parts of the code, I've added a github workflow that checks for broken links. This should keep the doc from getting too stale.
> Compiler architecture

- Sources/FrontEnd/TypeChecking/TypeChecker.swift
This PR let type information propagate from the leaves of infix expressions such that we can write `x + 1` when `x`  is other than `Int`.
> Fix type inference for numeric literals

- Sources/FrontEnd/TypeChecking/TypeChecker.swift
This PR adds a couple of memo cache to speed up hot methods in the type checker.
> Use memoization to speedup type checking

- Library/Hylo/Core/Numbers/Integers/UInt8.hylo
- Sources/Core/Diagnostic.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Tests/HyloTests/TestCases/TypeChecking/Skolemization.hylo
Note: regression observed in Tests/HyloTests/TestCases/TypeChecking/Skolemization.hylo. The test was simplified to reduce seemingly buggy interaction between traits and skolemization.
> Enforce associated type constraints

- .github/workflows/build-and-test.yml
Apparently it's a net loss: https://github.com/KyleMayes/install-llvm-action/commit/878985d084d4991346a5f6f26eae447ddc16457a
> Remove the use of github actions cache

- .github/workflows/doc-extraction.yml
Apparently it's a net loss: https://github.com/KyleMayes/install-llvm-action/commit/878985d084d4991346a5f6f26eae447ddc16457a
> Remove github action cache

- Library/Hylo/Print.hylo
- Sources/Core/AST/Decl/SynthesizedFunctionDecl.swift
- Sources/IR/Module.swift
Before this patch, `Hylo.stdout` was defined as a function that would "reopen" the standard output every time it got called, causing unexpected results on successive calls to `fwrite`.
> Fix the implementation of `print`

- Library/Library.swift
This change removes a hard-coded path to the standard library, which pointed to the pre-build source directory; i.e. directly to `//repo-root/Library/`. Instead, we use `Bundle.module.resourceURL` to point to the _post-build_ location of the standard library resource files.
> Use Bundle.module.resourceURL to point to Hylo standard library

- Sources/Driver/Driver.swift
- Sources/Driver/Process+Extensions.swift
- Sources/TestUtils/AnnotatedHyloFileTest.swift
- Tests/EndToEndTests/ExecutionTests.swift
- improve the diagnostic output when there are failures
- factor out synchronous subprocess launching.
> Make sure failing subprocesses cause thrown errors.

- Package.swift
Reverts hylo-lang/hylo#1027
I'm not sure what I was thinking.  It would have been a good idea to write that in the commit message.
> Restore needed plugin dependency

- Package.swift
- Sources/TestUtils/AnnotatedHyloFileTest.swift
- Sources/Utils/DirectedGraph.swift
- Tests/UtilsTests/DirectedGraphTests.swift
This algorithm will be used to detect trait refinement cycles.
> Implement DirectedGraph.isReachable(_:from:)

- StandardLibrary/Sources/Core/Hashable.hylo
- StandardLibrary/Sources/Core/Hasher.hylo
- StandardLibrary/Sources/Core/Numbers/Integers/Int.hylo
- StandardLibrary/Sources/Core/Numbers/Integers/Int32.hylo
- StandardLibrary/Sources/Core/Numbers/Integers/Int8.hylo
- StandardLibrary/Sources/Core/Numbers/Integers/UInt.hylo
- StandardLibrary/Sources/Core/Numbers/Integers/UInt8.hylo
- StandardLibrary/Sources/Core/Operators.hylo
- StandardLibrary/Sources/Core/Pointer.hylo
- StandardLibrary/Sources/Core/PointerToBuffer.hylo
This patch implements the 64-bit variant of FNV-1 as a universal hash function.
Note that using `Hasher` is not randomized, meaning that hashing the same value across multiple executions will produce the same value. We may want to modify this behavior, at least when `--freestanding` is not set, to reduce vulnerability to attacks based on hash collisions.
> Implement a universal hash function

- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/FrontEnd/TypedProgram.swift
- Sources/IR/Operands/Constant/FunctionReference.swift
It can happen that a function reference gets created with too many generic arguments when the emitter lowers a call in a generic context, unnecessary increasing the complexity of depolymorphization.
> Avoid the overspecializing function references

- Sources/FrontEnd/TypedProgram.swift
Parallel type checking is buggy on macOS in debug builds, seemingly because of UB. This patch disables it temporarily. It should be reverted once the bug is fixed.
> Disable parallel type checking on macOS

- Sources/Core/AST/AST.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/FrontEnd/TypedProgram.swift
- Sources/IR/Module.swift
- Tests/HyloTests/TestCases/TypeChecking/DuplicateCapture.hylo
This PR modifies name binding so that trait extensions are assumed to extend the implicit receiver parameter of the extended trait rather than the trait itself. In other words, given a trait extension `d`, `TypedProgram.declType[d]` is now the receiver parameter of a trait rather than a trait.
This change is a first step toward fixing #1111. The next one is to fix the creation of generic environments so that we can lift the restriction mentioned in 4734af6.
> Bind trait extensions to trait receivers

- .github/workflows/build-and-test.yml
- .github/workflows/doc-extraction.yml
- .spi.yml
- Sources/Driver/SourceLine+Extensions.swift
- Sources/IR/Operands/Constant/IntegerConstant.swift
Swift 5.11 requires you to acknowledge retroactive conformances, and on Windows that's the compiler version to test.
> Future-Swift compatibility.

- Sources/CodeGen/LLVM/Transpilation.swift
- Sources/IR/Emitter.swift
This PR fixes IR generation and codegen to properly handle assignments like the one below:
```swift
typealias A = Union<Int, String>
var x: A = "Bonjour"
&x = 42
if let y: Int = x { print(y) }
}
```
Assigning `42` to `x` requires an implicit conversion of `Int` to `Optional<Int>`. This conversion wasn't performed in the current implementation, which was causing UB.
> Handle implicit conversions on assignments

- Package.swift
- Sources/Driver/Driver.swift
- StandardLibrary/AST+Extensions.swift
- StandardLibrary/StandardLibrary.swift
- Tests/HyloTests/LoweringTests.swift
- Tests/HyloTests/TypeCheckerTests.swift
- Tests/ManglingTests/ManglingTests.swift
In an attempt to speed up testing, instead of parsing the library each time we need an AST for it as a starting point for testing, store hosted and/or freestanding ASTs in global constants, which are initialized once, lazily and thread-safely in Swift.
Also fixes #932.
- Debug:
- Parallel testing (`time swift test --parallel --skip-build`):
- Before: `440.54s user 23.45s system 834% cpu 55.578 total`
- After:    `441.36s user 23.85s system 834% cpu 55.723 total`
- Serial testing  (`time swift test --parallel --skip-build`):
- Before: `325.20s user 11.28s system 96% cpu 5:49.06 total`
- After:    `289.28s user 10.43s system 95% cpu 5:13.35 total`
- Release:
- Parallel testing (`time swift test --parallel --skip-build`):
- Before: `263.19s user 29.15s system 618% cpu 47.302 total`
- After: …
> Parse the standard library at most twice for host == target

- Sources/CodeGen/LLVM/Transpilation.swift
- Sources/CodeGen/LLVM/TypeLowering.swift
- Sources/Core/CompileTimeValues/CompileTimeValue.swift
- Sources/Core/Types/AnyType.swift
- Sources/Core/Types/BufferType.swift
- Sources/FrontEnd/TypeChecking/TypeChecker+Diagnostics.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/FrontEnd/TypedProgram.swift
- Sources/IR/Analysis/Module+AccessReification.swift
- Sources/IR/Analysis/Module+CloseBorrows.swift
- Sources/IR/Analysis/Module+Depolymorphize.swift
- Sources/IR/Analysis/Module+NormalizeObjectStates.swift
- Sources/IR/Analysis/Module+Ownership.swift
- Sources/IR/Emitter.swift
- Sources/IR/Mangling/DemangledType.swift
- Sources/IR/Mangling/Demangler.swift
- Sources/IR/Mangling/Mangler.swift
- Sources/IR/Mangling/ManglingOperator.swift
- Sources/IR/Operands/Constant/WordConstant.swift
- Sources/IR/Operands/Instruction/AdvancedByStrides.swift
- Sources/IR/Operands/Operand.swift
- Tests/EndToEndTests/TestCases/BufferInitialization.hylo
This PR implements some initial support for the compilation of buffer values:
- The type checker supports buffer expressions with constant sizes and can infer the type of buffer literals
- IR lowering can initialize buffer literals
- Code generation can emit pointer offset computation for buffer values
> Initial support for the compilation of buffers

- Sources/Driver/Driver.swift
- Sources/Utils/ResultOrError.swift
- StandardLibrary/AST+Extensions.swift
- StandardLibrary/StandardLibrary.swift
- Tests/HyloTests/LoweringTests.swift
- Tests/HyloTests/TypeCheckerTests.swift
- Tests/ManglingTests/ManglingTests.swift
If the standard library fails to parse we want to know why.
> Throw from AST construction instead of swallowing diagnostics.

- Sources/Core/Program.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/IR/Analysis/AbstractContext.swift
- Sources/IR/Analysis/Module+Depolymorphize.swift
- Sources/IR/Analysis/Module+NormalizeObjectStates.swift
- Sources/IR/Analysis/Module+Ownership.swift
- Sources/IR/Emitter.swift
- Sources/IR/Operands/Instruction/GenericArgument.swift
- Sources/IR/Operands/Instruction/GenericParameter.swift
- Tests/EndToEndTests/TestCases/GenericValueParameter.hylo
This PR stands up support for monomorphizing code involving generic value parameters.
Before depolymorphization, references generic value parameters are represented with a new IR instruction, `generic_argument`, which introduces initialized storage. In monomorphized form, generic value parameters are rewritten as local variables allocated and initialized before the first instruction of the generic function and uses of `generic_argument` are replaced by uses of the corresponding stack allocations.
> Initial support for monomorphization of generic value parameters

- Package.swift
- Plugins/TestGeneratorPlugin/TestGeneratorPlugin.swift
Don't treat the plugin inputs as source files and instead exclude them in Package.swift; then, instead of using target.sourceFiles(withSuffix: ".hylo") to find them, scrape target.directory for the .hylo files.  Whether they are treated as sources are not has no bearing on whether they get linked into the build dependency graph.
> Suppress the nasty unhandled source warnings

- Sources/Core/AST/AST.swift
- Sources/Core/AST/Decl/BindingDecl.swift
- Sources/Core/AST/Decl/ParameterDecl.swift
- Sources/Core/AST/Expr/FoldedSequenceExpr.swift
- Sources/Core/AST/NodeIDs/CallID.swift
- Sources/Core/Program.swift
- Sources/Core/Types/CallableType.swift
- Sources/Core/Types/CallableTypeParameter.swift
- Sources/FrontEnd/Parse/Parser+Diagnostics.swift
- Sources/FrontEnd/Parse/Parser.swift
- Sources/FrontEnd/Parse/ParserState.swift
- Sources/FrontEnd/TypeChecking/ArgumentResolutionResult.swift
- Sources/FrontEnd/TypeChecking/ConstraintSystem.swift
- Sources/FrontEnd/TypeChecking/Constraints/CallConstraint.swift
- Sources/FrontEnd/TypeChecking/Solution.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/FrontEnd/TypedProgram.swift
- Sources/IR/Emitter.swift
- Tests/EndToEndTests/TestCases/Implicits.hylo
- Tests/HyloTests/ParserTests.swift
- Tests/HyloTests/TestCases/Parsing/IllegalImplicit.hylo
This PR implements implicit parameters. The design of the feature is mostly copied from [Scala3](https://docs.scala-lang.org/tour/implicit-parameters.html). Syntactic choices are motivated by precedent in Scala and Haskell.
In summary:
- Parameters of functions, methods, initializers, and subscripts can be declared "implicit"
- The compiler passes values to implicit parameters automatically
- Bindings elligible as implicit arguments are implicit parameters and annotated local declarations
- Implicit resolution is entirely type-based
The motivation for this feature are twofold:
- Implicit parameters give us a way to alleviate the "argument piping" problem. Many functions in `hc` need "context" to compute properties of objects identified by some position in a collection. The ability to pass …
> Implement implicit parameters

- Docs/GenericEnvironments.md
- Sources/Core/AST/AST+Walk.swift
- Sources/Core/AST/Decl/GenericClause.swift
- Sources/Core/AST/Decl/WhereClause.swift
- Sources/Core/Types/GenericEnvironment.swift
- Sources/FrontEnd/Monotonic.swift
- Sources/FrontEnd/Parse/Parser.swift
- Sources/FrontEnd/TypeChecking/ConstraintSystem.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/IR/Mangling/Mangler.swift
- Tests/HyloTests/ParserTests.swift
- Tests/HyloTests/TestCases/TypeChecking/GenericEnvironment.hylo
This PR redesigns the construction of generic environments. A short explanation of the changes is given in the commit description of 3c142f4755601cb571f0c26110dbeb1ac8a78a82. `Docs/GenericEnvironments.md` provides more general information about generic environments and their construction.
This PR does not implement any consistency check on generic environments; that will be done as a separate patch.
> Improve the construction of generic environment

- Sources/IR/Emitter.swift
- Tests/HyloTests/TestCases/Lowering/ReturnInSubscript.hylo
Fixes the compiler trap observed in #1239
> Diagnose invalid return statements in non-sink subscripts

- Sources/CodeGen/LLVM/Transpilation.swift
- Sources/Core/AST/Decl/FunctionDecl.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
This PR implement supports for functions declared in Hylo and having an implementation defined externally.
Define the two following files:
- `main.hylo`:
```hylo
@external("initialize_in_cc")
fun initialize_externally(_ n: set Int)
var x: Int
initialize_externally(&x)
print(x)
}
```
- `hyloinit.cc`
```c++
#include <cstdint>
struct HyloInt {
int64_t value;
};
extern "C" {
// Note: 2nd parameter is the "Void" returned by `initialize_externally `.
// It will be passed as a null pointer from Hylo.
void initialize_in_cc(void* n, void*) {
auto* p = static_cast<HyloInt*>(n);
p->value = 42;
}
}
```
Build and run as follows:
```bash
c++ -c -std=c++20 -o hyloinit.o hyloinit.cc
llvm-ar r libhyloinit.a hyloinit.o
hc -L $(pwd) -l hyloinit -l c++ main.hylo
./main
```
The program …
> Extern functions

- Sources/Core/Types/GenericConstraint.swift
- Sources/FrontEnd/TypeChecking/TypeChecker+Diagnostics.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Tests/HyloTests/TestCases/TypeChecking/AssociatedTypeLookup.hylo
- Tests/HyloTests/TestCases/TypeChecking/AssociatedTypesWithConformances.hylo
This PR refactors name lookup in associated types to take conformance constraints into account. Conformances declared in all traits related to an associated types are now considered.
When performing qualified name lookup into an associated type of the form `T.X.Y`, one should not only consider the conformance constraints declared in the generic environment introducing `T`, but also those declared in the traits defining `X` and `Y` (see [AssociatedTypesWithConformances.hylo](https://github.com/hylo-lang/hylo/blob/2dff14c2380de9642ced5b717071632a3c4b138b/Tests/HyloTests/TestCases/TypeChecking/AssociatedTypesWithConformances.hylo) for an example).
> Fix name lookup in associated types

- Sources/Core/AST/AST.swift
- Sources/Core/Program.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/FrontEnd/TypedProgram.swift
- StandardLibrary/Sources/Core/Void.hylo
- Tests/HyloTests/TestCases/TypeChecking/ConformanceStructural.hylo
- Tests/HyloTests/TestCases/TypeChecking/NameLookupGeneric.hylo
- Tests/HyloTests/TestCases/TypeChecking/NestedGenerics.hylo
This PR makes the checker verifies that synthesized conformances for generic types are sounds. Previously the following declaration would type check, causing the compiler to crash during code generation if `A` was specialized for an indestructible type.
```hylo
type A<T>: Deinitializable {
var x: T
public memberwise init
}
```
> Make sure synthesized conformances are sound

- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/FrontEnd/TypedProgram.swift
- Sources/IR/CollectionWitness.swift
- Sources/IR/Emitter.swift
- Sources/IR/Operands/Instruction/Project.swift
Lowering a for loop in a trait extension caused the emitter to create unspecialized references to the subscript requirement in `Collection`, making the produced IR impossible to compile to LLVM.
> Fix the lowering of for loops in generic contexts

- Sources/Core/AST/AST.swift
- Sources/Core/AST/NodeIDs/NodeID.swift
- Sources/Core/Types/TypeAliasType.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/Utils/Collection+Extensions.swift
- Tests/HyloTests/TestCases/TypeChecking/ConditionalExtension.hylo
- Tests/HyloTests/TestCases/TypeChecking/ConditionalExtension2.hylo
This PR brings various improvements to the support of constraints on associated types. In particular, it fixes a couple of issues with the specialization of type aliases (which are typically used to form conformances) involving generic types.
> Improve the support of constraints on associated types

- StandardLibrary/Sources/Core/MutableCollection.hylo
- Tests/LibraryTests/TestCases/MutableCollectionTests.hylo
This PR adds a much more complete test of Hylo's rotate and makes it handle one important case that used to cause an assertion.
Except for not returning the new pivot, it actually does work!  So I'm sorry I doubted it (@kyouko-taiga). Amazingly, the swift implementation it was derived from failed [this test](https://github.com/hylo-lang/hylo/blob/045f1bb3f3313b532bb67dfc4285cf2fdb6dfce6/Tests/UtilsTests/CollectionExtensionsTests.swift#L68-L89).
As a student of rotate, I was expecting to see nested loops, which I have in my implementation.  But it's been too long since I worked on that algorithm, so I had forgotten the purpose of that nesting; I should have remembered that since it's O(N)  that nesting isn't strictly necessary; it just avoids a bunch of tests/branches.  
----
**update**: …
> Rotate robustness

- Sources/Core/AST/AST.swift
- Sources/IR/Mangling/Mangler.swift
- StandardLibrary/AST+Extensions.swift
Closes https://github.com/hylo-lang/hylo/issues/1213
Renames `isCoreModuleLoaded` to `coreModuleIsLoaded`
> Rename isCoreModuleLoaded to coreModuleIsLoaded

- Sources/Driver/Driver.swift
Closes https://github.com/hylo-lang/hylo/issues/842
I'm guessing that `module` is what we want here, but please correct me if I'm wrong.
> Correct the description of the -l option

- Sources/Core/AST/Decl/SynthesizedFunctionDecl.swift
- Sources/Core/Types/AnyType.swift
- Sources/Core/Types/LambdaType.swift
- Sources/FrontEnd/TypeChecking/ConstraintSystem.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/FrontEnd/TypedProgram.swift
- Sources/IR/Analysis/Module+Depolymorphize.swift
- Sources/IR/Emitter.swift
- StandardLibrary/Sources/Concurrency/Future.hylo
- StandardLibrary/Sources/Concurrency/Spawn.hylo
- Tests/HyloTests/TestCases/Lowering/Deinit.hylo
Code before the patch would ignore the trait bounds on a lambda's environment, allowing the compiler to synthesized a denitializer for `[E](T) -> U` even when `E` isn't `Deinitializable`.
> Fix the synthethization of structural conformances for lambda types

- Sources/Driver/Driver.swift
> Don't discard any diagnostics from parsing the standard library.

- Sources/Driver/Driver.swift
- Sources/FrontEnd/TypedProgram.swift
It's currently the cause of stack overflows. This change actually speeds up (`--parallel`) testing a little bit.
Fixes #1162
> Make parallel typechecking an experimental feature

- StandardLibrary/Sources/Concurrency/Future.hylo
- StandardLibrary/Sources/Concurrency/Spawn.hylo
Removes `FunctionWrapper`, which was a workaround #1246.
> Remove 'FunctionWrapper'

- .github/workflows/build-and-test.yml
- Docs/CLI.md
- Sources/Driver/Driver.swift
- Sources/Driver/OutputFileHandle.swift
- Sources/Driver/Version.swift
- Tests/DriverTests/DriverTests.swift
- Tools/set-hc-version.sh
Closes https://github.com/hylo-lang/hylo/issues/1120
- Adds a `-V` / `--version` flag to the compiler.
- Adds a script to set the compiler version. This is mainly for use in CI so that tags can be set as the version before building. The script can also be called during local development to set the version to a git hash. It could help when triaging issues to understand the commit the compiler was built at. This was the motivation for the original [issue](https://github.com/hylo-lang/hylo/issues/1120).
- Updates CI to set the version of the compiler either to a tag (if a `v` prefixed tag is pushed), or the git hash in all other cases.
> Support versioning the compiler

- .github/workflows/build-and-test.yml
These warning are caused by the action using a deprecated command on the GitHub Actions runner. The action author has fixed it in version [`0.7.4`](https://github.com/mattpolzin/swift-codecov-action/releases/tag/0.7.4), but we might as well bump to the latest version.
> Bump swift-codecov-action version to fix deprecation warnings

- Sources/Core/Types/UnionType.swift
- Sources/FrontEnd/TypeChecking/ConstraintSystem.swift
- Sources/FrontEnd/TypeChecking/Constraints/EqualityConstraint.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/IR/Emitter.swift
- StandardLibrary/Sources/Concurrency/Future.hylo
- StandardLibrary/Sources/Core/Range.hylo
- Tests/HyloTests/TestCases/TypeChecking/ConditionalStmt.hylo
- Tests/HyloTests/TestCases/TypeChecking/DoWhile.hylo
- Tests/HyloTests/TestCases/TypeChecking/Existential.hylo
- Tests/HyloTests/TestCases/TypeChecking/For.hylo
- Tests/HyloTests/TestCases/TypeChecking/UnionTypeGeneric.hylo
- Tests/HyloTests/TestCases/TypeChecking/While.hylo
- Tests/LibraryTests/TestCases/OptionalTests.hylo
This PR bans implicit conversions everywhere except at binding declaration (see [rationale](https://github.com/orgs/hylo-lang/discussions/1165)). We might eventually remove those as well.
> Ban most implicit conversions

- Sources/IR/Analysis/InliningPredicate.swift
- Sources/IR/Analysis/Module+Depolymorphize.swift
- Sources/IR/Analysis/Module+Inlining.swift
- Sources/IR/ModulePass.swift
- Sources/IR/Operands/Instruction/ConstantString.swift
- Sources/IR/Program.swift
This PR implements initial support for inlining IR function calls. Only functions without any control flow are inlined for now.
One can run the inliner with the following command:
```
hc --emit ir --transform inline input.hylo
```
> Stand up support for inlining

- Tests/LibraryTests/TestCases/ArrayTests.hylo
- Tests/LibraryTests/TestCases/IntTests.hylo
Found a couple of cases where test functions are not included in `main()`, and are therefore not executed.
> Fix tests where test functions are not being executed

- .github/dependabot.yml
Follow-up to the discussion in Slack.
GitHub actions that run on Node 16 are now deprecated, so you'll see messages like this in workflow runs.
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: dsaltares/fetch-gh-release-asset@a40c8b4a0471f9ab81bdf73a010f74cc51476ad4, compnerd/gha-setup-vsdevenv@a8b61f50b4ba55489b9ff4b1ccfbe65acb028b32. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
Most of these actions have probably already released updated versions that run on Node 20, or if they haven't, they will soon.
This PR enables dependabot for the GitHub Actions ecosystem so that Hylo will get automated PR requests for version updates of the actions in use.
I'm fairly sure …
> Enable dependabot for the github-actions ecosystem

- Tests/LibraryTests/TestCases/IntTests.hylo
Wraps Int tests which assume 64-bit arch in a conditional compilation block
This follows up on a `TODO` since https://github.com/hylo-lang/hylo/issues/1035 was completed.
> Test int64 conditionally on arch

- Sources/FrontEnd/Parse/Parser.swift
- Tests/EndToEndTests/TestCases/ExhaustiveBranchReturns.hylo
- Tests/HyloTests/ParserTests.swift
Closes https://github.com/hylo-lang/hylo/issues/977
- Returns `.let` as the introducer from `parseBindingIntroducer` when the current token is `_`
> Interpret wildcard without let as sugar for let wildcard

- Sources/IR/Emitter.swift
- Sources/IR/Operands/Instruction/ProjectBundle.swift
- Sources/IR/TypedProgram+Extensions.swift
- StandardLibrary/Sources/Array.hylo
- StandardLibrary/Sources/BitArray.hylo
- StandardLibrary/Sources/Concurrency/Future.hylo
- StandardLibrary/Sources/DynamicBuffer.hylo
- Tests/LibraryTests/TestCases/BitArrayTests.hylo
Fixes #1351
The lowering of subscript didn't properly handled mutation. Fixing it surfaced a few missing mutation markers in the standard library as well as a puzzling use of a local `inout` binding.
@lucteo it would be good if you had a look at 6b0e524a92502e0e80aa2576d3126df60c0d367b and tell if the refactoring looks OK.
> Fix write subscript

- .gitignore
- Package.resolved
- Package.swift
- Sources/CodeGen/LLVM/ConcreteTypeLayout.swift
- Sources/CodeGen/LLVM/LLVM+Word.swift
- Sources/CodeGen/LLVM/LLVMProgram.swift
- Sources/CodeGen/LLVM/Transpilation.swift
- Sources/CodeGen/LLVM/TypeLowering.swift
- Sources/Core/BuiltinFunction.swift
- Sources/Core/NativeInstruction.swift
- Sources/Driver/Driver.swift
Apparently needed for CMake/LLVM compatibility, since LLVM's own CMake files declare "LLVM" as a target.
This commit points hylo at the "cmake" branch of the Swifty-LLVM project until that branch can be merged to "main".
> Adopts the rename of the Swifty-LLVM module to SwiftyLLVM.

- Sources/CodeGen/LLVM/Transpilation.swift
- Sources/Core/Program.swift
- Sources/IR/Module.swift
LLVM can more aggressively optimize functions lowered with the Hylo passing convention if it knows they are private to a particular module.
> Use function linkage attribute to improve optimization opportunities

- .github/workflows/build-and-test.yml
From the docs it looks pretty robust; maybe the earlier failure (https://github.com/SwiftyLab/setup-swift/issues/236) was a fluke?
> Try the Swiftylab swift setup action again.

- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Tests/HyloTests/TestCases/TypeChecking/AssociatedTypeLookup.hylo
This PR fixes #1398.
The parts of the reproducers related to the issue are part of the tests (c821086bf453b9a6bb2fc8073503f57db5d0272e and 949def35cda1dd646a9062f36b47c7259eee585e). Note that the second reproducer involves another bug, already reported in #1401 (which this PR does not fix).
This PR also fixed #1400. Tests added for #1398 cover the reproducer of #1400.
> Fix associated type lookups involving aliases and generic parameters

- .github/workflows/build-and-test.yml
- Sources/CodeGen/LLVM/Transpilation.swift
- Sources/IR/Emitter.swift
- Sources/IR/Operands/Instruction/ConstantString.swift
- StandardLibrary/Sources/Core/Assert.hylo
- StandardLibrary/Sources/Core/Pointer.hylo
- StandardLibrary/Sources/Core/String.hylo
- StandardLibrary/Sources/Core/String/UTF8Array.hylo
- StandardLibrary/Sources/Print.hylo
This PR rewrites `String` so that it uses `UTF8Array` as its internal representation.
Note that 7bcab879d6053931a35f6f17cc287d4fffbb0f83 disables CI on Windows for debug builds because I was unable to identify the source of the issue, despite many attempts (see #1406).
> Improve the representation of `String`

- StandardLibrary/Sources/Concurrency/Future.hylo
- Tests/EndToEndTests/TestCases/Concurrency/mutating_spawn.hylo
Add example/test for concurrency with mutation.
Make the spawn functionality work with the newest version of `concore2full` library.
> Concurrency with mutation example

- StandardLibrary/Sources/Concurrency/Future.hylo
- StandardLibrary/Sources/Concurrency/Spawn.hylo
- Tests/EndToEndTests/TestCases/Concurrency/concurrent_sort.hylo
Using a mock for `spawn`/`await` so that the example runs without concurrent libraries.
> Concurrent sort example.

- .github/workflows/build-and-test.yml
Following https://github.com/hylo-lang/hylo/pull/1441, perhaps it makes sense to pin to `macos-13` to fix the build errors on `main`, until https://github.com/hylo-lang/hylo/pull/1439 is ready.
> Pin to macos-13 to fix build

- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/FrontEnd/TypedProgram.swift
- Sources/FrontEnd/Types/GenericEnvironment.swift
Generic environments are modified to store the constraints inherited from "parent" environments. As a result, gathering the conformances of a skolem or inspecting equivalence classes no longer requires an AST walk from a particular scope.
> Store inherited constraints and requirements in generic environments

- Package.swift
This PR adds support for importing the Hylo front-end as a library through SPM builds.
> Expose Frontend Library through Package.swfit

- Sources/CodeGen/LLVM/Transpilation.swift
- Sources/CodeGen/LLVM/TypeLowering.swift
- Sources/FrontEnd/CompileTimeValues/GenericArguments.swift
- Sources/FrontEnd/DeclReference.swift
- Sources/FrontEnd/TypeChecking/ConstraintSystem.swift
- Sources/FrontEnd/TypeChecking/NameResolutionContext.swift
- Sources/FrontEnd/TypeChecking/TypeChecker+Diagnostics.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/FrontEnd/TypedProgram.swift
- Sources/FrontEnd/Types/AnyType.swift
- Sources/FrontEnd/Types/BoundGenericType.swift
- Sources/FrontEnd/Types/MethodType.swift
- Sources/FrontEnd/Types/SubscriptImplType.swift
- Sources/FrontEnd/Types/UnionType.swift
- Sources/IR/Analysis/Module+DeadCodeElimination.swift
- Sources/IR/Analysis/Module+Depolymorphize.swift
- Sources/IR/Emitter.swift
- Sources/IR/Mangling/Mangler.swift
- Sources/IR/Module.swift
- Sources/IR/Operands/Constant/FunctionReference.swift
- Tests/HyloTests/TestCases/TypeChecking/ConditionalExtension.hylo
- Tests/HyloTests/TestCases/TypeChecking/WhereClause.hylo
This PR makes two changes to specialization:
- The ordering of generic parameters in `GenericArguments` is removed and stored in `BoundGenericType`, which is the only place where it actually makes sense.
- The collection of constraints on generic parameters associated with the resolution of a name is refactored to reduce pressure on constraint solving and produce better diagnostics.
> Refactor specialization maps

- Sources/FrontEnd/TypeChecking/SubstitutionMap.swift
- Sources/FrontEnd/Types/AnyType.swift
The "occurs-check" is a relatively cheap assertion that verifies unification doesn't construct infinite data structures.
> Implement occurs-check

- cmake/TopLevelDefaults.cmake
So we can update its main without breaking anything.
> Lock to a revision of Hylo-CMakeModules

- README.md
Watching the "Borrow Checking Hylo" talk shouldn't require Google harvesting your data, so I removed the tracker from the link.
> Remove tracker from link in README.md

- CONTRIBUTING.md
- README.md
I moved the contributing section to the beginning of our readme, so that it's not hidden below pages of setup guides. I also updated the meeting times, and added a time converter, so that people all around the world can quickly see when exactly the meetings happen.
I also added the slack and zoom links to CONTRIBUTING.md, which might be helpful on that page too, though I'm not entirely sure whether the redundancy is worth it, so I can remove that if needed.
> Update meeting times in README, make contributing section more apparent

- Sources/FrontEnd/AST/Decl/FunctionDecl.swift
- Sources/FrontEnd/BuiltinFunction.swift
- Sources/IR/Analysis/Module+NormalizeObjectStates.swift
- Sources/IR/Emitter.swift
- Sources/IR/Module.swift
- Sources/IR/Parameter.swift
- StandardLibrary/Sources/Concurrency/Future.hylo
- StandardLibrary/Sources/Core/Bitcast.hylo
- StandardLibrary/Sources/Core/String/UTF8Array.hylo
- Tests/HyloTests/TestCases/Lowering/DI.hylo
- Tests/HyloTests/TestCases/Lowering/MissingDeinit.hylo
Fixes #1500 and one of the bugs reported by #1499.
> Make sure `sink` parameter are deinitialized when a function returns

- Package.swift
- StandardLibrary/StandardLibrary.swift
Add support for choosing between standard library source taken from resources or the original sources.
Developers will need to set the HYLO_USE_BUILTIN_STDLIB environment variable to "true" if they want diagnostics to point to the original sources.
> Add support for choosing between standard library sources

- Sources/FrontEnd/DiagnosticSet.swift
- Sources/FrontEnd/TypeChecking/ConstraintSystem.swift
- Sources/FrontEnd/TypeChecking/Solution.swift
- Tests/HyloTests/TestCases/TypeChecking/Overloading.hylo
Keep diagnostics that are common to all solutions when an ambiguity is detected during constraint solving.
> Better ambiguity diagnostics

- Sources/CodeGen/LLVM/LLVMProgram.swift
- Sources/CodeGen/LLVM/Transpilation.swift
- Sources/CodeGen/LLVM/TypeLowering.swift
- Sources/Driver/Driver.swift
- Sources/FrontEnd/AST/Stmt/ConditionalCompilationStmt.swift
- Sources/FrontEnd/BuiltinFunction.swift
- Sources/FrontEnd/Parse/Parser.swift
- Sources/GenerateHyloFileTests/GenerateHyloFileTests.swift
- Tests/EndToEndTests/TestCases/ConditionalCompilation.hylo
- Tests/HyloTests/ParserTests.swift
This PR is finishing the work started by @Metalymph on logic operators in compile-time conditions (see #1358). The original PR was #1410.
> Add && and || operators to compile-time compilation conditions

- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/IR/Emitter.swift
- Sources/IR/TypedProgram+Extensions.swift
- Tests/EndToEndTests/TestCases/MethodBundle.hylo
It seems like keeping track of mutation markers to create ~method/~ subscript bundles isn't actually necessary for name resolution to pick the right candidates. Further access reification works better if we don't pre-filter the variants available on a free subscript bundle. For example:
```
subscript s(_ x: inout Int): Int {
let { yield x }
inout { yield &x }
}
var n = 0
inout m = s[&n]
}
```
Here, name resolution should _not_ filter out the `inout` variant only because the callee is not marked for mutation.
> Simplify variant selection

- Sources/CodeGen/LLVM/TypeLowering.swift
- Sources/FrontEnd/TypeChecking/ConstraintSystem.swift
- Sources/FrontEnd/TypeChecking/SubstitutionMap.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/FrontEnd/TypedProgram.swift
- Sources/FrontEnd/Types/AssociatedTypeType.swift
- Tests/HyloTests/TestCases/TypeChecking/AbstractType.hylo
This PR lets the type checker handle abstract associated types of the form `Array<X>.T.U`, where `X` is a generic parameter.
> Fix canonicalization of associated types

- Sources/FrontEnd/AST/AST.swift
- Sources/FrontEnd/AST/Decl/SynthesizedFunctionDecl.swift
- Sources/FrontEnd/Types/BuiltinType.swift
- Sources/IR/Emitter.swift
- Sources/IR/Mangling/Mangler.swift
- Sources/IR/Module.swift
- Sources/IR/Operands/Instruction/UnionDiscriminator.swift
- Tests/EndToEndTests/TestCases/SyntheticEquality.hylo
Everything is in the title. No more tedious `fun infix==(_ other: Self) -> Bool`.
> Implement equality operator synthesization

- Sources/CodeGen/LLVM/Transpilation.swift
- Sources/IR/Analysis/Module+NormalizeObjectStates.swift
- Sources/IR/Emitter.swift
- Sources/IR/InstructionTransformer.swift
- Sources/IR/Operands/Instruction/UnionSwitch.swift
- Tests/EndToEndTests/TestCases/UnionNarrowing.hylo
> Add an IR instruction to switch over the contents of a union

- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- StandardLibrary/Sources/Core/Optional.hylo
- Tests/HyloTests/TestCases/TypeChecking/ConditionalConformance.hylo
- Tests/LibraryTests/TestCases/OptionalTests.hylo
Now we can write this:
```
type Box<T> {
public let contents: T
public memberwise init
}
conformance Box: Equatable where T: Equatable {}
```
> Fix the checking of synthesizable conformances under a where clause

- Sources/CodeGen/LLVM/Transpilation.swift
- Sources/IR/Analysis/Module+AccessReification.swift
- Sources/IR/Analysis/Module+CloseBorrows.swift
- Sources/IR/Emitter.swift
- Sources/IR/InstructionTransformer.swift
- Sources/IR/Operands/Instruction/UnionSwitch.swift
- StandardLibrary/Sources/Core/Numbers/Integers/Int32.hylo
- StandardLibrary/Sources/Core/Numbers/Integers/Int64.hylo
- StandardLibrary/Sources/Core/Numbers/Integers/Int8.hylo
- StandardLibrary/Sources/Core/Numbers/Integers/UInt32.hylo
- StandardLibrary/Sources/Core/Numbers/Integers/UInt64.hylo
- StandardLibrary/Sources/Core/Numbers/Integers/UInt8.hylo
- Tests/EndToEndTests/TestCases/Concurrency/concurrent_sort.hylo
- Tests/EndToEndTests/TestCases/SyntheticCopy.hylo
- Tests/HyloTests/TestCases/Lowering/Narrowing.hylo
- Tests/LibraryTests/TestCases/MutableCollectionTests.hylo
- Tests/LibraryTests/TestCases/RangeTests.hylo
The following program is now legal:
```
fun f(_ x: Optional<Int>) {
if let y: Int = x { print(y) }
}
```
Previously, the compiler would complain that `x` can't be consumed because all narrowing conversions required a `sink` access on the source.
> Add support for non-consuming projections of union payloads

- Sources/FrontEnd/AST/AST+Walk.swift
- Sources/FrontEnd/AST/AST.swift
- Sources/FrontEnd/AST/NodeIDs/NodeKind.swift
- Sources/FrontEnd/AST/Pattern/OptionPattern.swift
- Sources/FrontEnd/Parse/Parser.swift
- Sources/FrontEnd/TypeChecking/TypeChecker+Diagnostics.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Tests/HyloTests/ParserTests.swift
- Tests/HyloTests/TestCases/TypeChecking/OptionPattern.hylo
Now we can write the following:
```
let x: Optional<Int> = 42 as _
if let y? = x { print(y) }
}
```
> Implement optional patterns

- Sources/IR/Emitter.swift
- StandardLibrary/Sources/Core/Optional.hylo
- Tests/LibraryTests/TestCases/OptionalTests.hylo
This PR adds a few methods to `Optional<T>`.
> Improve the API of `Optional`

- .typos.toml
- Sources/FrontEnd/AST/Decl/SynthesizedFunctionDecl.swift
- Sources/FrontEnd/CompileTimeValues/CompileTimeValue.swift
- Sources/FrontEnd/TypedProgram.swift
- Sources/IR/Analysis/Module+Depolymorphize.swift
- Sources/IR/Emitter.swift
- Sources/IR/FunctionID.swift
- Sources/IR/Mangling/DemangledEntity.swift
- Sources/IR/Mangling/DemangledQualification.swift
- Sources/IR/Mangling/DemangledSymbol.swift
- Sources/IR/Mangling/DemangledSynthesizedFunction.swift
- Sources/IR/Mangling/DemangledType.swift
- Sources/IR/Mangling/Demangler.swift
- Sources/IR/Mangling/Mangler.swift
- Sources/IR/Mangling/ManglingOperator.swift
- Sources/IR/Mangling/TypedProgram+Mangling.swift
- Tests/ManglingTests/MangledStrings.swift
- Tests/ManglingTests/ManglingTests.swift
> Fix the mangling algorithm

- Sources/CodeGen/LLVM/LLVMProgram.swift
- Sources/CodeGen/LLVM/Transpilation.swift
- Sources/CodeGen/LLVM/TypeLowering.swift
This PR makes two changes:
- Guarantee that the LLVM IR types we generate have no duplicate within a single LLVM module
- Guarantee that string constants have no duplicate within a single LLVM module
> Improve code generation to reduce sizes of binaries

- StandardLibrary/Sources/Core/Collection.hylo
- Tests/LibraryTests/TestCases/CollectionTests.hylo
Partially implements #1511. The algorithm on `MutableCollection` is blocked by #1510.
> Implement some algorithms on `Collection`

- Sources/FrontEnd/AST/Decl/GenericParameterDecl.swift
- Sources/FrontEnd/Parse/Parser.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- StandardLibrary/Sources/Array.hylo
- Tests/EndToEndTests/TestCases/GenericValueParameter.hylo
- Tests/HyloTests/ParserTests.swift
- Tests/HyloTests/TestCases/TypeChecking/GenericParameters.hylo
- Tests/HyloTests/TestCases/TypeChecking/GenericTypeAlias.hylo
- Tests/HyloTests/TestCases/TypeChecking/NameLookupGeneric3.hylo
This PR adds a new introducer to distinguish between generic type and term parameters based on syntax, retiring the previous detection algorithm which was based on a handful of tricks.
> Use an introducer to determine the kind of a generic parameter

- Sources/FrontEnd/AST/AST+Walk.swift
- Sources/FrontEnd/AST/NodeIDs/NodeKind.swift
- Sources/FrontEnd/AST/Stmt/ConditionalBindingStmt.swift
- Sources/FrontEnd/Parse/Parser.swift
- Sources/FrontEnd/TypeChecking/TypeChecker+Diagnostics.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/IR/Emitter.swift
- Tests/EndToEndTests/TestCases/ConditionalBinding.hylo
- Tests/HyloTests/ParserTests.swift
- Tests/HyloTests/TestCases/TypeChecking/ConditionalBinding.hylo
This PR implements full support for conditional binding statements, e.g:
```
fun print_int_or_trap(_ x: Union<Int, Bool>) {
let y: Int = x else { fatal_error() }
print(y)
}
```
> Implement conditional binding statements

- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/FrontEnd/TypedProgram.swift
- Sources/IR/Emitter.swift
- Sources/IR/IteratorWitness.swift
- Tests/EndToEndTests/TestCases/For.hylo
This PR implements support for loops like the following:
```
for sink let n in 0 ..< 10 { print(n) }
```
> Implement consuming for loops

- Docs/Compiler/CompilerArchitecture.md
- Docs/Compiler/Modules.puml
- make the relative point to the right paths
- Add "Important files" column to the stages of compilation
- Add "Important compiler modules" section with diagram and explanations
> Update compiler architecture documentation.

- CONTRIBUTING.md
- CONVENTIONS.md
CompilerArchitecture.md and CodeFormatting.md have moved to the Compiler subdirectory.
> Fix broken markdown references
