- Sources/AST/CaptureTable.swift
- Sources/AST/Decl.swift
- Sources/AST/Pattern.swift
- Sources/Parse/Lexer.swift
- Sources/Parse/Parser.swift
- Sources/Parse/Token.swift
- Sources/VIL/Builder.swift
- Sources/VIL/Emitter.swift
- Sources/VIL/LValueEmitter.swift
- Sources/VIL/RValueEmitter.swift
- Tests/ParseTests/LexerTests.swift
- Tests/ValTests/TestCases/Eval/Async.val
- Tests/ValTests/TestCases/Eval/FortyTwo.val
- Tests/ValTests/TestCases/Eval/PartialApply.val
- Tests/ValTests/TestCases/Eval/PatternMatching.val
- Tests/ValTests/TestCases/Eval/TypeCasting.val
- Tests/ValTests/TestCases/TypeChecker/AbstractType.val
- Tests/ValTests/TestCases/TypeChecker/BoundedPolymorphism.val
- Tests/ValTests/TestCases/TypeChecker/Extensions.val
- Tests/ValTests/TestCases/TypeChecker/NameBinding.val
- Tests/ValTests/TestCases/TypeChecker/Overloading.val
- Tests/ValTests/TestCases/TypeChecker/PatternMatching.val
- Tests/ValTests/TestCases/TypeChecker/Specialization.val
- Tests/ValTests/TestCases/TypeChecker/TupleMember.val
Not completely tested because of https://github.com/val-lang/val/issues/9
> Change val keyword to let.

- Sources/Compiler/AST/Decl.swift
- Sources/Compiler/AST/FileUnit.swift
- Sources/Compiler/AST/NodePrinter.swift
- Sources/Compiler/Compiler.swift
- Sources/Compiler/Parsing/Parser.swift
- Sources/Compiler/TypeChecking/CaptureCollector.swift
This complexity wasn't buying anything and will help us get rid of the classes eventually.
> Nix BuiltinUnit/SourceUnit types

- Sources/Compiler/AST/NodeIDs/DeclID.swift
- Sources/Compiler/AST/NodeIDs/ExprID.swift
- Sources/Compiler/AST/NodeIDs/NodeID.swift
- Sources/Compiler/AST/NodeIDs/PatternID.swift
- Sources/Compiler/AST/NodeIDs/ScopeID.swift
- Sources/Compiler/AST/NodeIDs/StmtID.swift
- Sources/Compiler/AST/NodeIDs/TypeExprID.swift
I needed something more descriptive to be able to easily grok the code.
> Rename NodeID.T to NodeID.Subject, fix some docs.

- Sources/Compiler/Parse/SourceFile.swift
SourceFiles don't have "identifiers"
> Fix a comment

- Sources/Compiler/Parse/Parser.swift
See https://github.com/apple/swift/issues/62136
> Workaround swiftc bug

- Sources/Compiler/Parse/Parser.swift
> Quick-n-dirty expr/typeExpr unification

- Sources/Compiler/Parse/Parser.swift
- Tests/ValTests/ParserTests.swift
> nix obsolete unionTypeExpr

- Sources/Compiler/CXX/CXXModule.swift
- Sources/Compiler/CXX/CXXScopedBlock.swift
- Sources/Compiler/CXX/CXXTranspiler.swift
- Sources/Compiler/CXX/CXXVoidCast.swift
- Tests/ValTests/TestCases/CXX/FactorialExample.val
*Why*
Make progress in implementing the factorial example.
*What*
- start transpilng local var bindings
- add void-cast operation to represent operations for which return value is ignored
*Testing*
Unit tests pass
> Start borrowed local binding

- Tests/ValTests/EmitterTests.swift
- Tests/ValTests/TestCases/Lowering/Factorial.val
This PR adds a simple test case to run the IR emitter and execute mandatory analysis and transformation passes.
> Add a simple test case for IR lowering and analysis

- Sources/Core/Types/AnyType.swift
The utility will be used to implement subtyping tests.
> Implement a utility to compare types

- .github/workflows/check-format.yml
- Docs/CodeFormatting.md
- Sources/CLI/main.swift
- Sources/CodeGen/CXX/CXXFunctionDecl.swift
- Sources/Core/AST/AST.swift
- Sources/Core/AST/DeclLocator.swift
- Sources/Core/Constraints/DisjunctionConstraint.swift
- Sources/Core/Constraints/FunctionCallConstraint.swift
- Sources/Core/Constraints/OverloadConstraint.swift
- Sources/Core/SourceFile.swift
- Sources/FrontEnd/Parse/Lexer.swift
- Sources/FrontEnd/Parse/Parser+Diagnostics.swift
- Sources/FrontEnd/Parse/Parser.swift
- Sources/FrontEnd/Parse/ParserState.swift
- Sources/FrontEnd/Parse/Token.swift
- Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
- Sources/FrontEnd/TypeChecking/ConstraintSolver.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/IR/Analysis/DefiniteInitializationPass.swift
- Sources/IR/Analysis/DominatorTree.swift
- Sources/IR/Emitter.swift
- Sources/IR/Module+Description.swift
- Sources/IR/Module.swift
- Sources/IR/Operands/Instruction/CallInstruction.swift
- Sources/Utils/Algorithms.swift
- Tests/ValTests/EmitterTests.swift
- Tests/ValTests/Utils/TestAnnotation.swift
Upgrade swift-format to the version that contains Dave's patch, so that we add spaces around range operators.
> Swift format upgrade

- Sources/Core/SourceFile.swift
- Tests/ValTests/CXXTests.swift
- Tests/ValTests/EmitterTests.swift
- Tests/ValTests/ParserTests.swift
- Tests/ValTests/TypeCheckerTests.swift
- Tests/ValTests/Utils/AnnotatedValFileTest.swift
- Tests/ValTests/Utils/DefaultTestAnnotationHandler.swift
> Further testing simplification

- .github/workflows/build-and-test.yml
Add Windows to the matrix for the CI validation.
> workflows: add Windows to the matrix

- Sources/CLI/main.swift
- Sources/FrontEnd/Parse/Parser.swift
- Tests/ValTests/ParserTests.swift
@kyouko-taiga is this a valid change?  It passes all tests.  I need an answer for the driver work.
> Encapsulation

- .github/workflows/build-and-test.yml
Getting rid of --enable-code-coverage on Windows
> Try to fix Windows build

- Sources/CodeGen/CXX/CXXTranspiler.swift
- Sources/CodeGen/CXX/Decl/CXXLocalVarDecl.swift
- Sources/CodeGen/CXX/Expr/CXXInfixExpr.swift
- Sources/CodeGen/CXX/README.md
- Tests/ValTests/TestCases/CXX/Stmt/AssignStmt.val
Support for local variable is at its infancy.
Adding CXX translation test for assign statements
> Emit CXX code for assign statements, expression statements, and local variables

- Sources/FrontEnd/TypeChecking/TypeChecker+ConstraintGeneration.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
This PR refactors how constraint generation operates on patterns for consistency with expressions.
> Refactor pattern constraints

- Sources/Core/AST/AST+WellFormedness.swift
- Sources/Core/AST/AST.swift
- Sources/Core/AST/DeclLocator.swift
- Sources/Core/AST/NodeIDs/NodeID.swift
- Sources/Core/Program.swift
- Sources/Core/ScopedProgram.swift
- Sources/Core/TypedNode.swift
- Sources/FrontEnd/Parse/Parser.swift
- Sources/FrontEnd/TypeChecking/CaptureCollector.swift
- Sources/FrontEnd/TypeChecking/TypeChecker+ConstraintGeneration.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Tests/ValTests/CaptureCollectorTests.swift
> Eliminate 'NodeID.init(rawValue:)'

- Sources/FrontEnd/TypeChecking/TypeChecker+ConstraintGeneration.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
> Rename 'infer(typeOf:...)' to 'inferType(of:...)'

- .github/workflows/build-and-test.yml
- Sources/IR/Analysis/ImplicitReturnInsertionPass.swift
- Tests/ValTests/TestCases/Lowering/ImplicitReturn.val
The pass would make the compiler crash for empty functions.
> Fix return insertion

- .gitignore
- Sources/CodeGen/CXX/CXXCodeWriter.swift
- Sources/CodeGen/CXX/CXXComment.swift
- Sources/CodeGen/CXX/CXXTranspiler.swift
- Sources/CodeGen/CXX/TranslationUnitCode.swift
- Sources/Core/TypedProgram.swift
- Sources/ValCommand/ValCommand.swift
- Tests/ValTests/CXXTests.swift
> Start translating Val standard library to C++

- Sources/IR/Emitter.swift
- Tests/ValTests/TestCases/Lowering/DoWhile.val
We can't write a passing test for while loops because of a bug in definite initialization (DI). Because I'm already working on refactoring DI on another branch, I'll submit the test on another PR that we can merge once DI is fixed.
> Emit IR for do-while and while loops

- README.md
- Sources/ValCommand/ValCommand.swift
Fixes: #261 and Fixes: #45
This is my first time to use Swift, I wonder if there is any problem
> Make Val compiler to find Clang on Windows

- Sources/CodeGen/CXX/CXXCodeWriter.swift
CI is failing when it tries to compile transpiled code on Ubuntu.
> Fix failing CI on Ubuntu

- Sources/CodeGen/CXX/CXXCodeWriter.swift
- Sources/CodeGen/CXX/CodeFormatter.swift
- Sources/CodeGen/CXX/Expr/CXXIdentifier.swift
- Sources/Core/AST/DeclLocator.swift
- Tests/ValTests/CXXIdentifierTests.swift
> Sanitize C++ identifiers

- Sources/FrontEnd/Parse/Parser.swift
- Tests/ValTests/TestCases/Parsing/ArgumentLists.val
> Fix the comma-separated list parser

- Sources/Core/AST/Name.swift
- Sources/Core/Constraints/FunctionCallConstraint.swift
- Sources/Core/DiagnosticSet.swift
- Sources/Core/Types/CallableType.swift
- Sources/Core/Types/TupleType.swift
- Sources/Core/Types/TypeVariable.swift
- Sources/FrontEnd/TypeChecking/ConstraintSolver.swift
- Sources/FrontEnd/TypeChecking/TypeChecker+ConstraintGeneration.swift
- Sources/FrontEnd/TypeChecking/TypeChecker+Diagnostics.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Tests/ValTests/TestCases/TypeChecking/CallGenericFunction.val
- Tests/ValTests/TestCases/TypeChecking/Destructuring.val
> Refactor constraint solving

- Sources/Core/AST/NodeIDs/NodeKind.swift
- Sources/Core/Program.swift
- Sources/Core/ScopedProgram.swift
- Sources/FrontEnd/TypeChecking/ConstraintSystem.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/IR/Emitter.swift
- Sources/Utils/Collection+Extensions.swift
- Tests/UtilsTests/CollectionExtensionsTests.swift
- Tests/ValTests/NodeKindTests.swift
> Fix invalid definition of NodeKind's inequality operator

- Sources/Core/TypedProgram.swift
- Sources/FrontEnd/TypeChecking/GenericEnvironment.swift
- Sources/FrontEnd/TypeChecking/TypeChecker+ConstraintGeneration.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
> Get rid of needless success flags

- .github/workflows/build-and-test.yml
- .gitignore
- Package.resolved
- Package.swift
- README.md
- Sources/ValCommand/ValCommand.swift
- Tests/ValCommandTests/ValCommandTests.swift
> Support the MSVC and GCC & add `--cc-flags` command line argument & Update `swift-argument-parser` to version `1.2.0`

- Sources/IR/Analysis/ControlFlowGraph.swift
- Sources/IR/Analysis/DominatorTree.swift
- Sources/Utils/DoublyLinkedList.swift
This PR implements Cooper et al.'s fast dominance algorithm. See https://www.cs.rice.edu/~keith/EMBED/dom.pdf
> Fix the construction of the dominator tree

- Package.swift
- Tests/EndToEndTests/ExecutionTests.swift
- Tests/EndToEndTests/TestCases/Factorial.val
We compile and execute all test .val files. We expect that all the compiled programs to execute successfully.
> Add support for end-to-end tests.

- Sources/Core/Constraints/ConformanceConstraint.swift
- Sources/Core/Constraints/EqualityConstraint.swift
- Sources/Core/Constraints/FunctionCallConstraint.swift
- Sources/Core/Constraints/MemberConstraint.swift
- Sources/Core/Constraints/MergingConstraint.swift
- Sources/Core/Constraints/OverloadConstraint.swift
- Sources/Core/Constraints/ParameterConstraint.swift
- Sources/Core/Constraints/SubtypingConstraint.swift
- Sources/Core/Constraints/TupleMemberConstraint.swift
- Sources/Core/SourceFile.swift
- Sources/Core/TypeRelations.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/IR/Analysis/AbstractContext.swift
- Sources/IR/Emitter.swift
- Sources/Utils/DirectedGraph.swift
- Sources/Utils/MVS.swift
- Tests/UtilsTests/CollectionExtensionsTests.swift
> MVS meets FP (again)

- Sources/CodeGen/CXX/CXXTranspiler.swift
- Sources/CodeGen/LLVM/LLVMProgram.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Tests/EndToEndTests/TestCases/Factorial.val
> Fix prefix operators

- Package.resolved
- Sources/CodeGen/LLVM/LLVM+Extensions.swift
- Sources/Core/Types/WitnessTableType.swift
- Sources/IR/Emitter.swift
- Sources/IR/Module.swift
- Sources/IR/Operands/Constant/Constant.swift
- Sources/IR/Operands/Constant/MetatypeConstant.swift
- Sources/IR/Operands/Constant/WitnessTable.swift
- Sources/IR/Operands/Constant/WitnessTableType.swift
- Sources/IR/Operands/Instruction/WrapAddrInstruction.swift
- Sources/IR/Operands/Instruction/WrapInstruction.swift
- Tests/EndToEndTests/TestCases/Existential.val
Testing the changes require additional changes to be submitted in another PR as this one is growing big already.
> Implement basic support for generating witness tables

- Sources/CodeGen/CXX/CXXModule+Extensions.swift
- Sources/CodeGen/CXX/CXXTranspiler.swift
- Sources/CodeGen/CXX/Decl/CXXMethod.swift
- Sources/CodeGen/CXX/Expr/CXXIdentifier.swift
- Tests/ValTests/TestCases/CXX/Decl/Operators.val
> Translate operator definitions to C++

- Sources/Core/Types/AnyType.swift
- Sources/Core/Types/BoundGenericType.swift
- Sources/Core/Types/CallableTypeParameter.swift
- Sources/Core/Types/ConformanceLensType.swift
- Sources/Core/Types/LambdaType.swift
- Sources/Core/Types/MetatypeType.swift
- Sources/Core/Types/MethodType.swift
- Sources/Core/Types/ParameterType.swift
- Sources/Core/Types/RemoteType.swift
- Sources/Core/Types/SubscriptImplType.swift
- Sources/Core/Types/SubscriptType.swift
- Sources/Core/Types/SumType.swift
- Sources/Core/Types/TupleType.swift
- Sources/Core/Types/TypeProtocol.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
This LOE violation has only been reproduced by me so far and it's not yet clear whether it's spurious, or a real violation that is only caught dynamically.
> work around / fix dynamic LOE violation

- Sources/Core/Diagnostic.swift
- Sources/Core/DiagnosticSet.swift
- Sources/FrontEnd/Parse/Parser+Diagnostics.swift
- Sources/FrontEnd/Parse/Parser.swift
- Sources/FrontEnd/TypeChecking/TypeChecker+Diagnostics.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/IR/Analysis/Module+NormalizeObjectStates.swift
They really should have their own type; this is a step in that direction.
> Make diagnostic notes more first-class

- Sources/Core/TypedProgram.swift
- Sources/IR/Analysis/Module+AccessReification.swift
- Sources/IR/Analysis/Module+Depolymorphize.swift
- Sources/IR/Emitter.swift
- Sources/IR/Operands/Instruction/ProjectBundleInstruction.swift
- Sources/IR/Operands/Instruction/ProjectInstruction.swift
This PR fixes #678. However, proper will require synthetization of `Deinitializable` for generic types.
> Monomorphize generic projections

- Sources/IR/Analysis/Module+NormalizeObjectStates.swift
- Tests/ValTests/TestCases/Lowering/ProjectionEscape.val
This PR fixes the second problem observed in #677.
> Detect illegal projection escapes

- Sources/IR/Module+Description.swift
The purpose of this change is to improve the debuggability of the IR textual representation.
> Add register types in the IR textual representation

- Library/Val/Core/Double.val
- Library/Val/Core/Float.val
- Sources/CodeGen/LLVM/LoweredProgram+Extensions.swift
- Sources/Core/NativeInstruction.swift
- Sources/Core/Types/BuiltinType.swift
- Sources/FrontEnd/TypeChecking/TypeChecker+ConstraintGeneration.swift
- Sources/IR/Emitter.swift
- Sources/IR/Operands/Constant/FloatingPointConstant.swift
- Tests/ValTests/BuiltinFunctionTests.swift
- Tests/ValTests/TestCases/Lowering/Init.val
- Tests/ValTests/TestCases/Lowering/NumericLiteral.val
- Tests/ValTests/TestCases/TypeChecking/BindingTypeInferenceWithHints.val
- Tests/ValTests/TestCases/TypeChecking/CallGenericFunction.val
- Tests/ValTests/TestCases/TypeChecking/CallGenericUnnamedSubscript.val
- Tests/ValTests/TestCases/TypeChecking/ConditionalExpr.val
- Tests/ValTests/TestCases/TypeChecking/ExtensionOfImport.val
- Tests/ValTests/TestCases/TypeChecking/FloatLiteralExpr.val
- Tests/ValTests/TestCases/TypeChecking/GenericParameters.val
- Tests/ValTests/TestCases/TypeChecking/IntegerLiteralExpr.val
- Tests/ValTests/TestCases/TypeChecking/MatchExpr.val
- Tests/ValTests/TestCases/TypeChecking/Overloading.val
- Tests/ValTests/TestCases/TypeChecking/TupleMembers.val
> Rationalize names of floating types

- README.md
> Reformat audio/video links & Add ADSP 137 To Podcast Links

- Sources/CodeGen/LLVM/Transpilation.swift
- Sources/IR/Analysis/Module+Depolymorphize.swift
- Sources/IR/Analysis/Module+NormalizeObjectStates.swift
- Sources/IR/Analysis/Module+Ownership.swift
- Sources/IR/Module.swift
Only just noticed this disturbance
> Re-alphabetize some code.

- Sources/Core/AST/AST.swift
- Sources/Core/AST/Decl/SynthesizedFunctionDecl.swift
- Sources/Core/Conformance.swift
- Sources/Core/Program.swift
- Sources/Core/SourceFile.swift
- Sources/Core/SourceRange.swift
- Sources/Core/TypedProgram.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/IR/Analysis/Module+Depolymorphize.swift
- Sources/IR/Emitter.swift
- Sources/IR/Function.swift
- Sources/IR/FunctionID.swift
- Sources/IR/Mangling/Mangler.swift
- Sources/IR/Module+Description.swift
- Sources/IR/Module.swift
- Sources/TestUtils/XCTest+Shims.swift
For the poor souls who have to debug the IR.
> Better IR names

- README.md
just adding another row in the table.
> Add ACCU "Concurrency Approaches: Past, Present, and Future" talk to README.txt

- Sources/Core/AST/Decl/ImplicitCapture.swift
- Sources/Core/AST/Decl/InitializerDecl.swift
- Sources/Core/AST/Expr/FoldedSequenceExpr.swift
- Sources/Core/AST/NodeIDs/DeclID.swift
- Sources/Core/Conformance.swift
- Sources/Core/Program.swift
- Sources/Core/Types/ExistentialType.swift
- Sources/Core/Types/ParameterType.swift
- Sources/Core/Types/TupleType.swift
- Sources/Core/Types/TypeFlags.swift
- Sources/Core/Types/UnionType.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/Utils/CustomWitnessedSet.swift
This patch makes a handful of small changes extracted from a larger PR to come.
> Miscellaneous refactorings

- Sources/FrontEnd/Parse/Lexer.swift
- Sources/GenerateValFileTests/GenerateValFileTests.swift
- Sources/GenerateValFileTests/main.swift
Fix failing test that was not detected on CI.
> Fix invalid exponent token detection

- Sources/Core/AST/BundledNode.swift
- Sources/Core/TypedProgram.swift
- Sources/FrontEnd/Parse/Lexer.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/GenerateValFileTests/GenerateValFileTests.swift
- Sources/GenerateValFileTests/main.swift
- Sources/IR/Mangling/Mangler.swift
> Depluralize property maps

- Tests/EndToEndTests/TestCases/TupleKeyPath.val
Added a test for Tuple Key Path
Related to https://github.com/val-lang/val/issues/783
> Tuple key path test

- Sources/Core/CompileTimeValues/GenericArguments.swift
- Sources/IR/Analysis/Module+Depolymorphize.swift
- Sources/IR/Emitter.swift
- Sources/IR/Module.swift
- Sources/IR/Program.swift
> Keep track of generic arguments passed to synthesized declarations

- Sources/FrontEnd/TypeChecking/TypeChecker.swift
This PR fixes the regression mentioned in #813.
> Fix the instantiation of generic parameters in name expressions

- .github/workflows/build-and-test.yml
- .github/workflows/doc-extraction.yml
- .github/workflows/format-check.yml
Supposedly this could speed up CI for us.
> Try to use .build directory cacheing.

- Sources/IR/Analysis/Module+Depolymorphize.swift
Single-commit PR to fix monomorphization of functions with control flow.
> Monomorphize all basic blocks before instructions

- .github/workflows/format-check.yml
See https://github.com/swift-actions/setup-swift/issues/591#issuecomment-1685710678
> Use the swift docker image to run format check.

- Sources/Core/AST/AST.swift
- Sources/Core/DiagnosticSet.swift
- Sources/FrontEnd/AST+Extensions.swift
- Sources/FrontEnd/Parse/Parser.swift
See https://github.com/apple/swift/issues/68102
> localizedDescription is useless; avoid it.

- .github/workflows/build-and-test.yml
See https://github.com/hylo-lang/hylo/issues/805
> Fix misleading windows build name

- Sources/Core/AST/AST+Walk.swift
- Sources/Core/Types/LambdaType.swift
- Sources/Core/Types/MethodType.swift
- Sources/Core/Types/SubscriptImplType.swift
- Sources/Core/Types/SubscriptType.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
> Avoid needless use of 'Sequence.forEach' (#930)

- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Tests/HyloTests/TestCases/TypeChecking/NameLookupWithAlias.hylo
> Fix name lookup through type aliases

- .github/workflows/doc-extraction.yml
> Revert "Add conditional to publishing actions"

- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Tests/HyloTests/TestCases/TypeChecking/NameLookupGeneric.hylo
> Fix the construction of instantiation contexts

- Library/Hylo/DynamicBuffer.hylo
- Tests/LibraryTests/TestCases/DynamicBufferTests.hylo
This enables one to access the dynamic buffer's elements.
> Add DynamicBuffer.first_element_address()

- Sources/IR/Analysis/Module+NormalizeObjectStates.swift
- Sources/IR/Emitter.swift
- Tests/EndToEndTests/TestCases/ExhaustiveBranchReturns.hylo
Fixes https://github.com/hylo-lang/hylo/issues/711
> Exhaustive branch returns

- Sources/Core/SourceRange.swift
> Make SourceRange constructor public

- Sources/FrontEnd/TypeChecking/Constraints/CallConstraint.swift
- Sources/IR/Callee.swift
- Sources/IR/Emitter.swift
- Sources/IR/Operands/Constant/FunctionReference.swift
This issue partially addresses #1007 but doesn't fix it for memberwise initializers.
> Lower direct calls to custom initializers

- .github/workflows/build-and-test.yml
Attempt to work around https://github.com/apple/swift-package-manager/issues/7069
> Fix parallel testing / coverage interaction

- Sources/TestUtils/AnnotatedHyloFileTest.swift
> val => hylo

- Sources/TestUtils/AnnotatedHyloFileTest.swift
Trying to get at least some diagnostic information on #1130.
RIght away in local testing, I got:
```
Test Case '-[LibraryTests.LibraryTests test_compileAndRun_OptionalTests]' started.
/Users/dave/src/hylo/Tests/LibraryTests/TestCases/OptionalTests.hylo:1: error: -[LibraryTests.LibraryTests test_compileAndRun_OptionalTests] : success was expected, but processing failed with thrown error: NonzeroExit(
terminationStatus: 6,
standardOutput: "/Users/dave/src/hylo/Tests/LibraryTests/TestCases/OptionalTests.hylo:10: precondition failure\n",
standardError: "",
commandLine: ["/var/folders/f3/48cjbvxd0sx81ld0qm__zqrc0000gn/T/83CF26FA-3963-4623-AE36-1256AC0165C9"])
```
So it's working!
> Report the details of unexpected processing failures.

- Sources/Core/AST/Decl/SynthesizedFunctionDecl.swift
- Sources/Core/Program.swift
- Sources/Driver/Driver.swift
- Sources/Driver/Process+Extensions.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/IR/Mangling/Mangler.swift
- Tests/HyloTests/TestCases/TypeChecking/ConformanceWithRefinement.hylo
> Handle conformance to traits refining imported traits

- .github/workflows/doc-extraction.yml
- Package.resolved
- Package.swift
Don't make everyone pay for documentation extraction.  Also try to run it entirely on Linux in CI.
> Try to speed up builds and testing by bypassing docc plugin builds

- Sources/FrontEnd/Parse/Parser.swift
- Sources/FrontEnd/Parse/ParserState.swift
- Tests/HyloTests/ParserTests.swift
> Fix the parsing of method calls on integer literals

- Sources/FrontEnd/TypeChecking/TypeChecker.swift
This PR makes no functional change. It only factors out code from large functions and tries to improve docs.
> Refactor name component resolution

- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- StandardLibrary/Sources/Core/Numbers/Integers/BinaryInteger.hylo
- StandardLibrary/Sources/Core/Numbers/Integers/UInt.hylo
- StandardLibrary/Sources/Core/Numbers/Integers/UInt8.hylo
- StandardLibrary/Sources/Core/Numbers/Numeric.hylo
This PR fixes #1047 and #1086.
> Fix infinite recursion caused by nested type aliases

- Sources/Core/AST/AST.swift
- Sources/IR/Emitter.swift
- Tests/HyloTests/TestCases/Lowering/InvalidRvalue.hylo
> Diagnose invalid uses of a subscript as a rvalue

- Sources/IR/Emitter.swift
- StandardLibrary/Sources/Array.hylo
- StandardLibrary/Sources/Core/CollectionOfOne.hylo
- Tests/HyloTests/TestCases/Lowering/IllegalMove.hylo
> Diagnose illegal attempts to move values

- StandardLibrary/Sources/Core/MutableCollection.hylo
- Tests/LibraryTests/TestCases/MutableCollectionTests.hylo
This one is for you @sean-parent!
The test is a bit clunky but we don't have a good way to write unit tests yet.
> Implement 'MutableCollection.rotate'

- Tests/HyloTests/TestCases/TypeChecking/GenericArguments.hylo
Add a regression test for #592 "Compiler crashes when assigning variable to unbound generic type"
> Add a regression test for #592

- Sources/FrontEnd/Parse/Parser+Diagnostics.swift
- Sources/FrontEnd/Parse/Parser.swift
- Tests/HyloTests/TestCases/Parsing/UnterminatedNestedComment.hylo
> Rationalize unterminated comment/string diagnostics.

- Sources/FrontEnd/Parse/Parser.swift
- Sources/FrontEnd/TypeChecking/ConstraintSystem.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/FrontEnd/TypedProgram.swift
Closes https://github.com/hylo-lang/hylo/issues/1213
Follow-up with some ones that were missed.
> Rename boolean properties of the form isNounAdjective => nounIsAdjective

- Sources/IR/Emitter.swift
- Sources/IR/Operands/Instruction/ConstantString.swift
- Tests/EndToEndTests/TestCases/Pragma.hylo
> Fix the stack leak caused by the lowering of '#file' pragmas

- Package.swift
SPM figures that stuff out apparently.
> Remove no-longer-needed unsafe flag

- Package.swift
- Sources/Core/AST/AST+CoreTraits.swift
- Sources/Core/AST/AST.swift
- Tests/HyloTests/ASTTests.swift
Merging this into #1205 has no effect on the failure.  @kyouko-taiga you might need to fix this problem.  Also I don't know how to write a test for this change.
> Encode/Decode coreTraits as part of AST

- Sources/FrontEnd/AST+UseCollection.swift
- Tests/EndToEndTests/TestCases/Lambda.hylo
This PR fixes Implicit captures involving qualified names
> Fix the identification of implicit captures

- Sources/IR/Analysis/Module+AccessReification.swift
- Sources/IR/Analysis/Module+DeadCodeElimination.swift
- Sources/IR/Analysis/Module+Simplification.swift
- Sources/IR/Emitter.swift
- Sources/IR/Module.swift
- Sources/Utils/DoublyLinkedList.swift
This PR implements constant folding for address computations and eliminates redundant accesses. The goal of these changes is to produce a more compact IR to speedup IR passes and LLVM code generation.
> Improve the quality of the refined IR

- Package.swift
- README.md
- Sources/FrontEnd/TypeChecking/ConstraintSystem.swift
- Sources/IR/Emitter.swift
See c2fa5dc4c6296b712e1046d289710bbf07da08ad for rationale.
> Bump Swift version to 5.9

- Sources/Core/AST/AST+Walk.swift
- Sources/Core/AST/Decl/CapturingDecl.swift
- Sources/Core/AST/Decl/FunctionDecl.swift
- Sources/Core/AST/Decl/SubscriptDecl.swift
- Sources/FrontEnd/AST+UseCollection.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Tests/EndToEndTests/TestCases/ExplicitCaptures.hylo
> Fix capture detection

- Package.resolved
- Package.swift
> Points to the "main" branch of Swifty-LLVM

- Tests/EndToEndTests/TestCases/DefaultImplementation.hylo
Fixes #693 using the unit test suggested by @peter-evans.
> Add a test calling implementations inherited through conformance

- StandardLibrary/Sources/Core/Bool.hylo
- Tests/LibraryTests/TestCases/BoolTests.hylo
> Richer bool interface redux

- Sources/GenerateHyloFileTests/GenerateHyloFileTests.swift
- Sources/TestUtils/AnnotatedHyloFileTest.swift
> Generate compile-and-run tests applying optimizations

- Sources/FrontEnd/TypedProgram.swift
- StandardLibrary/Sources/Core/Lifetime.hylo
- StandardLibrary/Sources/Core/Numbers/Integers/Int.hylo
- StandardLibrary/Sources/Core/Numbers/Integers/Int64.hylo
- StandardLibrary/Sources/Core/Numbers/Integers/UInt.hylo
- StandardLibrary/Sources/Core/Numbers/Integers/UInt64.hylo
- StandardLibrary/Sources/Core/Pointer.hylo
- StandardLibrary/Sources/Core/PointerToMutable.hylo
- StandardLibrary/Sources/UTF8Array.hylo
Details of the implementation are written in the comments of `UTF8Array.hylo`.
> Reimplement `UTF8Array`

- Sources/FrontEnd/Parse/Parser+Diagnostics.swift
- Sources/FrontEnd/Parse/Parser.swift
- Sources/FrontEnd/Parse/ParserState.swift
- Tests/HyloTests/TestCases/Parsing/IllegalTypealias.hylo
> Improve diagnostics around ill-formed typealias declarations

- Sources/Core/Program.swift
- Sources/FrontEnd/TypeChecking/TypeChecker+Diagnostics.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Tests/HyloTests/TestCases/TypeChecking/RecursiveParameter.hylo
> Gracefully diagnose recursive definitions

- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Tests/HyloTests/TestCases/TypeChecking/NameLookupWithDottedPath.hylo
> Fix constraint generation for long name expressions

- Sources/FrontEnd/Conformance.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/FrontEnd/TypedProgram.swift
- Sources/IR/Analysis/Module+Depolymorphize.swift
- Sources/IR/Emitter.swift
- Sources/IR/Module.swift
See d0f59d9feb266644a25ee2ad904f712809e086f1 for details.
> Choose better names for concepts related to conformances

- .github/workflows/build-and-test.yml
…by going back to using compnerd's swift-setup action there.
> Fix Windows Swift setup

- .github/workflows/build-and-test.yml
It's flaking out even in release builds.
https://github.com/hylo-lang/hylo/actions/runs/9133417859/job/25116843815
> Stop testing with SPM on Windows

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/workflows/build-and-test.yml
- .github/workflows/doc-extraction.yml
- Package.swift
Upgraded Swift version to 5.10
> Upgrade to Swift 5.10

- Sources/FrontEnd/SourceFile.swift
- Tests/ManglingTests/ManglingTests.swift
> Remove needless parameter in constructor of 'SourceFile'

- Sources/FrontEnd/AccessEffectSet.swift
- Sources/IR/Analysis/Module+AccessReification.swift
- Sources/IR/Analysis/Module+Ownership.swift
- Sources/IR/Module.swift
- StandardLibrary/Sources/Array.hylo
- Tests/EndToEndTests/TestCases/Autoclosure.hylo
- Tests/EndToEndTests/TestCases/Concurrency/concurrent_sort.hylo
- Tests/EndToEndTests/TestCases/Concurrency/mutating_spawn.hylo
- Tests/EndToEndTests/TestCases/ExplicitCaptures.hylo
- Tests/EndToEndTests/TestCases/Lambda.hylo
- Tests/HyloTests/AccessEffectSetTests.swift
- Tests/HyloTests/TestCases/Lowering/IllegalPropertyMutation.hylo
> Fix ownership analysis

- Sources/IR/Analysis/Module+Depolymorphize.swift
This PR fixes the issue caused by merging of #1551
> Make sure monomorphized functions have canonical generic arguments

- Sources/Driver/Driver.swift
- Sources/FrontEnd/TypeChecking/TypeChecker.swift
- Sources/FrontEnd/TypedProgram.swift
New lines are not covered because this patch is about adding debugging options to the compiler. A separate PR could add tests that simply exercise these flags.
> Add an option to log requirement systems after completion

- Docs/GenericDispatch.md
@kyouko-taiga PTAL. Content below the horizontal line is all unfinished material that may or may not eventually be used.
> Begin GenericDispatch document

- Docs/GenericDispatch.md
s/Static Choice/Static Selection/ and reordered a paragraph for clarity.
> Use "static selection"

- Package.resolved
- cmake/TopLevelDefaults.cmake
"Ensure proper alignment for store instructions. (#83)"
> Update modules to include Swifty-LLVM change

- Sources/IR/Emitter.swift
And fix a bug in the emission of `break` that is detected by this enforcement.
> Try to enforce stack discipline

- Sources/IR/Module.swift
- Tests/EndToEndTests/TestCases/BufferAssignment.hylo
> Fix the detection of immutable buffer sources

- Sources/IR/Analysis/Module+DefiniteLifetimeAnalysis.swift
- Sources/IR/Analysis/Module+Depolymorphize.swift
- Sources/IR/Emitter.swift
@kyouko-taiga PTAL to make sure you think this is on the right track.  Obviously comments are outdated, etc and the whole thing is WIP
> Emitter DSL

- Sources/FrontEnd/AccessEffectSet.swift
- Sources/IR/Analysis/Module+AccessReification.swift
- Sources/IR/Analysis/Module+CallBundleReification.swift
- Sources/IR/Analysis/Module+Depolymorphize.swift
- Sources/IR/Analysis/Module+NormalizeObjectStates.swift
- Sources/IR/Emitter.swift
- Sources/IR/Module.swift
- Sources/IR/Operands/Instruction/Access.swift
This reverts commit 906f231d27d26aee654d429fceaf32bf297afb27, reversing changes made to d12241df1cf00949ecacd4d288d2a4d381608e5b.
> Revert "Emitter DSL/refactoring, phase 1 (#1669)"

- .github/workflows/devcont.yml
- ContextualMutation.swift
- Sources/IR/#%2Aediff-merge%2A#7pk4u5#
- Sources/IR/#%2Aediff-merge%2A#TtRWpD#
- Sources/IR/#%2Aediff-merge%2A#hBSp5d#
- Sources/IR/#%2Aediff-merge%2A#hysi5F#
- Sources/IR/#%2Aediff-merge%3C2%3E%2A#ctMDbF#
- Sources/IR/#%2Aediff-merge%3C2%3E%2A#x86EVf#
- Sources/IR/Analysis/#%2Aediff-merge%2A#0YV34d#
- Sources/IR/Analysis/Module+Depolymorphize.swift
- Sources/IR/Emitter.swift
- success-timing.txt
- x.ir
Going to take this step by step to try to locate the hang.
> Emitter DSL, redux

- Sources/IR/Analysis/Module+Depolymorphize.swift
- Sources/IR/Analysis/Module+NormalizeObjectStates.swift
- Sources/IR/Emitter.swift
This is currently failing for reasons I don't understand.
> Emitter: contextual _lowering

- Sources/IR/Analysis/Module+Depolymorphize.swift
- Sources/IR/Analysis/Module+NormalizeObjectStates.swift
- Sources/IR/Emitter.swift
- Removed redundant  _lowering calls
- Improved Naming
- Added missing documentation
- Removed needless optionality
> Emitter Cleanups
